from rdflib.namespace import (
    DefinedNamespace as DefinedNamespace,
    Namespace as Namespace,
)
from rdflib.term import URIRef as URIRef

class GEO(DefinedNamespace):
    dggsLiteral: URIRef
    geoJSONLiteral: URIRef
    gmlLiteral: URIRef
    kmlLiteral: URIRef
    wktLiteral: URIRef
    Feature: URIRef
    FeatureCollection: URIRef
    Geometry: URIRef
    GeometryCollection: URIRef
    SpatialObject: URIRef
    SpatialObjectCollection: URIRef
    asGML: URIRef
    asWKT: URIRef
    asGeoJSON: URIRef
    asKML: URIRef
    asDGGS: URIRef
    coordinateDimension: URIRef
    dimension: URIRef
    hasMetricArea: URIRef
    hasMetricLength: URIRef
    hasMetricPerimeterLength: URIRef
    hasMetricSpatialAccuracy: URIRef
    hasMetricSpatialResolution: URIRef
    hasMetricSize: URIRef
    hasMetricVolume: URIRef
    hasSerialization: URIRef
    isEmpty: URIRef
    isSimple: URIRef
    spatialDimension: URIRef
    defaultGeometry: URIRef
    ehContains: URIRef
    ehCoveredBy: URIRef
    ehCovers: URIRef
    ehDisjoint: URIRef
    ehEquals: URIRef
    ehInside: URIRef
    ehMeet: URIRef
    ehOverlap: URIRef
    hasArea: URIRef
    hasBoundingBox: URIRef
    hasCentroid: URIRef
    hasDefaultGeometry: URIRef
    hasGeometry: URIRef
    hasLength: URIRef
    hasPerimeterLength: URIRef
    hasSize: URIRef
    hasSpatialAccuracy: URIRef
    hasSpatialResolution: URIRef
    hasVolume: URIRef
    rcc8dc: URIRef
    rcc8ec: URIRef
    rcc8eq: URIRef
    rcc8ntpp: URIRef
    rcc8ntppi: URIRef
    rcc8po: URIRef
    rcc8tpp: URIRef
    rcc8tppi: URIRef
    sfContains: URIRef
    sfCrosses: URIRef
    sfDisjoint: URIRef
    sfEquals: URIRef
    sfIntersects: URIRef
    sfOverlaps: URIRef
    sfTouches: URIRef
    sfWithin: URIRef
