from rdflib.container import *
from rdflib import plugin as plugin, query as query, util as util
from rdflib.graph import (
    ConjunctiveGraph as ConjunctiveGraph,
    Dataset as Dataset,
    Graph as Graph,
)
from rdflib.namespace import (
    BRICK as BRICK,
    CSVW as CSVW,
    DC as DC,
    DCAT as DCAT,
    DCMITYPE as DCMITYPE,
    DCTERMS as DCTERMS,
    DOAP as DOAP,
    FOAF as FOAF,
    Namespace as Namespace,
    ODRL2 as ODRL2,
    ORG as ORG,
    OWL as OWL,
    PROF as PROF,
    PROV as PROV,
    QB as QB,
    RDF as RDF,
    RDFS as RDFS,
    SDO as SDO,
    SH as SH,
    SKOS as SKOS,
    SOSA as SOSA,
    SSN as SSN,
    TIME as TIME,
    VANN as VANN,
    VOID as VOID,
    XMLNS as XMLNS,
    XSD as XSD,
)
from rdflib.term import (
    BNode as BNode,
    IdentifiedNode as IdentifiedNode,
    Literal as Literal,
    Node as Node,
    URIRef as URIRef,
    Variable as Variable,
)

__all__ = [
    "URIRef",
    "BNode",
    "IdentifiedNode",
    "Literal",
    "Node",
    "Variable",
    "Namespace",
    "Dataset",
    "Graph",
    "ConjunctiveGraph",
    "BRICK",
    "CSVW",
    "DC",
    "DCAT",
    "DCMITYPE",
    "DCTERMS",
    "DOAP",
    "FOAF",
    "ODRL2",
    "ORG",
    "OWL",
    "PROF",
    "PROV",
    "QB",
    "RDF",
    "RDFS",
    "SDO",
    "SH",
    "SKOS",
    "SOSA",
    "SSN",
    "TIME",
    "VANN",
    "VOID",
    "XMLNS",
    "XSD",
    "util",
    "plugin",
    "query",
    "NORMALIZE_LITERALS",
]

NORMALIZE_LITERALS: bool
