from typing import Any

__all__ = ["Event", "Dispatcher"]

class Event:
    def __init__(self, **kw) -> None: ...

class Dispatcher:
    def set_map(self, amap: dict[Any, Any]): ...
    def get_map(self): ...
    def subscribe(self, event_type, handler): ...
    def dispatch(self, event) -> None: ...
