__all__ = ["Resource"]

class Resource:
    def __init__(self, graph, subject) -> None: ...
    @property
    def graph(self): ...
    @property
    def identifier(self): ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...
    def __unicode__(self): ...
    def add(self, p, o) -> None: ...
    def remove(self, p, o=None) -> None: ...
    def set(self, p, o) -> None: ...
    def subjects(self, predicate=None): ...
    def predicates(self, o=None): ...
    def objects(self, predicate=None): ...
    def subject_predicates(self): ...
    def subject_objects(self): ...
    def predicate_objects(self): ...
    def value(self, p=..., o=None, default=None, any: bool = True): ...
    def items(self): ...
    def transitive_objects(self, predicate, remember=None): ...
    def transitive_subjects(self, predicate, remember=None): ...
    def qname(self): ...
    def __iter__(self): ...
    def __getitem__(self, item): ...
    def __setitem__(self, item, value) -> None: ...
