$schema: https://json-schema.org/draft/2020-12/schema
$id: https://wikibase.org/schemas/s3-statement/3.0.0.json
title: S3 Statement Snapshot
description: Immutable statement snapshot stored in S3. First-class citizen statements
  with hash-based deduplication and full revision tracking.
type: object
required:
- schema_version
- content_hash
- statement
- created_at
properties:
  schema_version:
    type: string
    pattern: ^\d+\.\d+\.\d+$
    description: Schema version (MAJOR.MINOR.PATCH)
  content_hash:
    type: integer
    description: Rapidhash integer of statement JSON for deduplication and storage
      key.
    minimum: -922337203685477581
    examples:
    - 987654321012345678
    - -918273876123456789
  statement:
    type: object
    required:
      - mainsnak
      - type
      - rank
    properties:
      mainsnak:
        type: integer
        description: Hash of the main snak.
      type:
        type: string
        enum:
          - statement
      rank:
        type: string
        enum:
          - preferred
          - normal
          - deprecated
      qualifiers:
        type: integer
        description: Rapidhash of qualifiers dict for deduplication.
      references:
        type: array
        description: List of reference hashes.
        items:
          type: integer
  created_at:
    type: string
    format: date-time
    description: ISO 8601 timestamp when this statement was created.
    examples:
    - '2026-01-05T10:00:00Z'
