from _typeshed import Incomplete
from collections.abc import Generator

class ResponsibleGenerator:
    cleanup: Incomplete
    gen: Incomplete
    def __init__(self, gen, cleanup) -> None: ...
    def __del__(self) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...

class ConcurrentStore:
    store: Incomplete
    def __init__(self, store) -> None: ...
    def add(self, triple) -> None: ...
    def remove(self, triple) -> None: ...
    def triples(self, triple) -> Generator[Incomplete]: ...
    def __len__(self) -> int: ...
