@startuml Detailed Model Components

title Wikibase Backend - Detailed Model Components

package "Models" as Models #LightCyan {
    "AliasValue" as AliasValue
    "Aliases" as Aliases
    "Aliases" as AliasesResponse
    "Backlink" as Backlink
    "BacklinkStatisticsData" as BacklinkStatisticsData
    "BacklinkStatistics" as BacklinkStatisticsResponse
    "Backlinks" as BacklinksResponse
    "BatchEndorsementStats" as BatchEndorsementStatsResponse
    "CleanupOrphaned" as CleanupOrphanedResponse
    "DeduplicationStats" as DeduplicationStatsResponse
    "Description" as DescriptionResponse
    "DescriptionValue" as DescriptionValue
    "Descriptions" as DescriptionsResponse
    "EndorsementList" as EndorsementListResponse
    "Endorsement" as EndorsementResponse
    "EndorsementStats" as EndorsementStatsResponse
    "Entities" as EntitiesResponse
    "EntityAliases" as EntityAliasesResponse
    "EntityChange" as EntityChange
    "EntityDelete" as EntityDeleteResponse
    "EntityDescriptions" as EntityDescriptionsResponse
    "EntityHistoryEntry" as EntityHistoryEntry
    "EntityJsonImport" as EntityJsonImportResponse
    "EntityLabels" as EntityLabelsResponse
    "EntityList" as EntityListResponse
    "EntityListing" as EntityListing
    "EntityMetadataBatch" as EntityMetadataBatchResponse
    "EntityMetadata" as EntityMetadataResponse
    "EntityRedirect" as EntityRedirectResponse
    "Entity" as EntityResponse
    "EntityRevert" as EntityRevertResponse
    "EntityRevision" as EntityRevisionResponse
    "EntitySitelinks" as EntitySitelinksResponse
    "EntityState" as EntityState
    "EntityStatements" as EntityStatementsResponse
    "FullRevision" as FullRevisionResponse
    "GeneralStatsData" as GeneralStatsData
    "GeneralStats" as GeneralStatsResponse
    "HealthCheck" as HealthCheckResponse
    "Health" as HealthResponse
    "Id" as IdResponse
    "JsonSchema" as JsonSchema
    "Label" as LabelResponse
    "LabelValue" as LabelValue
    "Labels" as LabelsResponse
    "Message" as MessageResponse
    "MetadataContent" as MetadataContent
    "MetadataLoad" as MetadataLoadResponse
    "MostUsedStatements" as MostUsedStatementsResponse
    "Properties" as PropertiesResponse
    "PropertyCounts" as PropertyCounts
    "PropertyCounts" as PropertyCountsResponse
    "PropertyHashes" as PropertyHashesResponse
    "PropertyList" as PropertyListResponse
    "Protection" as ProtectionResponse
    "Qualifier" as QualifierResponse
    "RangeStatus" as RangeStatus
    "RangeStatuses" as RangeStatuses
    "RawEntityData" as RawEntityData
    "RawRevision" as RawRevisionResponse
    "RedirectBatch" as RedirectBatchResponse
    "Reference" as ReferenceResponse
    "RevisionMetadata" as RevisionMetadataResponse
    "SingleEndorsementStats" as SingleEndorsementStatsResponse
    "SitelinkValue" as SitelinkValue
    "Sitelinks" as SitelinksResponse
    "StatementBatch" as StatementBatchResponse
    "StatementEndorsementStats" as StatementEndorsementStats
    "StatementHashResult" as StatementHashResult
    "Statement" as StatementResponse
    "Statements" as StatementsResponse
    "Terms" as TermsResponse
    "Thank" as ThankResponse
    "ThanksList" as ThanksListResponse
    "TopEntityByBacklinks" as TopEntityByBacklinks
    "Turtle" as TurtleResponse
    "UserActivity" as UserActivityResponse
    "UserCreate" as UserCreateResponse
    "UserPreferences" as UserPreferencesResponse
    "UserStatsData" as UserStatsData
    "UserStats" as UserStatsResponse
    "WatchCounts" as WatchCounts
    "WatchlistToggle" as WatchlistToggleResponse
    "WikibasePredicates" as WikibasePredicatesResponse
    "WorkerHealthCheck" as WorkerHealthCheckResponse
}

@enduml