@startuml Detailed Service Components

title Wikibase Backend - Detailed Service Components

package "Services" as Services #LightGreen {
    "BacklinkStatistics" as BacklinkStatisticsService
    "Enumeration" as EnumerationService
    "GeneralStats" as GeneralStatsService
    "Hash" as HashService
    "IdRange" as IdRange
    "IdRangeManager" as IdRangeManager
    "Redirect" as RedirectService
    "Statement" as StatementService
    "UserStats" as UserStatsService
}

@enduml