from _typeshed import Incomplete
from aiokafka.errors import (
    KafkaTimeoutError as KafkaTimeoutError,
    LeaderNotAvailableError as LeaderNotAvailableError,
    NotLeaderForPartitionError as NotLeaderForPartitionError,
    ProducerClosed as ProducerClosed,
)
from aiokafka.record.default_records import (
    DefaultRecordBatchBuilder as DefaultRecordBatchBuilder,
)
from aiokafka.structs import RecordMetadata as RecordMetadata
from aiokafka.util import (
    create_future as create_future,
    get_running_loop as get_running_loop,
)
from collections.abc import Sequence

class BatchBuilder:
    def __init__(
        self,
        batch_size,
        compression_type,
        *,
        is_transactional: int = 0,
        key_serializer=None,
        value_serializer=None,
    ) -> None: ...
    def append(self, *, timestamp, key, value, headers: Sequence = []): ...
    def close(self) -> None: ...
    def size(self): ...
    def record_count(self): ...

class MessageBatch:
    future: Incomplete
    def __init__(self, tp, builder, ttl) -> None: ...
    @property
    def tp(self): ...
    @property
    def record_count(self): ...
    def append(
        self, key, value, timestamp_ms, _create_future=..., headers: Sequence = []
    ): ...
    def done(
        self,
        base_offset,
        timestamp=None,
        log_start_offset=None,
        _record_metadata_class=...,
    ) -> None: ...
    def done_noack(self) -> None: ...
    def failure(self, exception) -> None: ...
    async def wait_drain(self, timeout=None) -> None: ...
    def expired(self): ...
    def drain_ready(self) -> None: ...
    def reset_drain(self) -> None: ...
    def set_producer_state(
        self, producer_id, producer_epoch, base_sequence
    ) -> None: ...
    def get_data_buffer(self): ...
    def is_empty(self): ...
    @property
    def retry_count(self): ...

class MessageAccumulator:
    def __init__(
        self,
        cluster,
        batch_size,
        compression_type,
        batch_ttl,
        *,
        txn_manager=None,
        loop=None,
    ) -> None: ...
    async def flush(self) -> None: ...
    async def flush_for_commit(self) -> None: ...
    def fail_all(self, exception) -> None: ...
    async def close(self) -> None: ...
    async def add_message(
        self, tp, key, value, timeout, timestamp_ms=None, headers: Sequence = []
    ): ...
    def data_waiter(self): ...
    def reenqueue(self, batch) -> None: ...
    def drain_by_nodes(self, ignore_nodes, muted_partitions=...): ...
    def create_builder(self, key_serializer=None, value_serializer=None): ...
    async def add_batch(self, builder, tp, timeout): ...
