$schema: https://json-schema.org/draft/2020-12/schema
$id: https://wikibase.org/schemas/s3-reference/1.0.0.json
title: S3 Reference Snapshot
description: Immutable reference snapshot stored in S3. References with hash-based deduplication and full revision tracking.
type: object
required:
- schema_version
- content_hash
- reference
- created_at
properties:
  schema_version:
    type: string
    pattern: ^\d+\.\d+\.\d+$
    description: Schema version (MAJOR.MINOR.PATCH)
  content_hash:
    type: integer
    description: Rapidhash integer of reference JSON for deduplication and storage key.
    minimum: -922337203685477581
    examples:
    - 987654321012345678
    - -918273876123456789
  reference:
    type: object
    description: Reference object containing snaks and metadata.
    required:
      - snaks
    properties:
      hash:
        type: string
        description: Hash of the reference for deduplication.
      snaks:
        type: object
        description: Hash references to snaks providing the reference data.
        patternProperties:
          ^P[0-9]+$:
            type: array
            items:
              type: integer
              description: Hash of the snak.
      snaks-order:
        type: array
        description: Order of properties in the snaks object.
        items:
          type: string
          pattern: ^P[0-9]+$
  created_at:
    type: string
    format: date-time
    description: ISO 8601 timestamp when this reference was created.
    examples:
    - '2026-01-05T10:00:00Z'