FROM python:3.13-slim

RUN apt-get update && apt-get install -y wget git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PYTHONPATH=/app

COPY ../var/requirements-create-tables.txt ./
COPY pyproject.toml /app/pyproject.toml

RUN pip install --no-cache-dir -r requirements-create-tables.txt

COPY ./src/ ./
COPY ./scripts/ ./scripts/

CMD ["python", "-m", "models.workers.create", "tables", "setup"]