FROM python:3.13-slim

RUN apt-get update && apt-get install -y wget git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PYTHONPATH=/app

COPY requirements-api.txt ./
COPY pyproject.toml /app/pyproject.toml

RUN pip install --no-cache-dir -r requirements-api.txt

COPY ./src/ ./
COPY ./scripts/ ./scripts/

EXPOSE 8080

CMD ["uvicorn", "models.rest_api.main:app", "--host", "0.0.0.0", "--port", "8080"]
