FROM python:3.13-alpine AS builder
WORKDIR /app
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev
COPY pyproject.toml poetry.lock ./
RUN pip install --no-cache-dir poetry \
    && poetry install --no-root --no-interaction --only ttl-worker

FROM python:3.13-alpine
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY pyproject.toml /app/pyproject.toml
COPY src/ ./
ENV PYTHONPATH=/app
CMD ["python", "-m", "models.workers.ttl_dumps.ttl_dump_worker"]
