# We keep the commands in the compose file
FROM python:3.13-alpine

ARG REQUIREMENTS_HASH=initial
RUN echo "Building with requirements hash: $REQUIREMENTS_HASH"

WORKDIR /app

COPY ./var/requirements-dev.txt ./

RUN pip install --no-cache-dir -r requirements-dev.txt

RUN pip install --no-cache-dir poetry

COPY ./tests/ ./tests/
COPY ./src/ ./
COPY ./test_data/ ./test_data/
COPY ./schemas/ ./schemas/
COPY pyproject.toml .
COPY poetry.lock .

RUN poetry install --no-interaction --no-root

ENV PYTHONPATH=/app
ENV REST_API_URL=http://api:8000
