# We keep the commands in the compose file
FROM python:3.13-slim AS builder

ARG REQUIREMENTS_HASH=initial
RUN echo "Building with requirements hash: $REQUIREMENTS_HASH"

RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-dev.txt ./

RUN pip install --no-cache-dir -r requirements-dev.txt

RUN pip install --no-cache-dir poetry

COPY pyproject.toml .
COPY poetry.lock .

RUN poetry install --no-interaction --no-root

FROM python:3.13-slim

ARG REQUIREMENTS_HASH=initial
RUN echo "Building with requirements hash: $REQUIREMENTS_HASH"

RUN apt-get update && apt-get install -y curl git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY ./tests/ ./tests/
COPY ./src/ ./
COPY ./test_data/ ./test_data/
COPY ./schemas/ ./schemas/

ENV PYTHONPATH=/app
ENV REST_API_URL=http://api:8000
