FROM python:3.13-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PYTHONPATH=/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src/ ./
COPY ./scripts/ ./scripts/

EXPOSE 8000

CMD ["uvicorn", "models.rest_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
