# We keep the commands in the compose file
FROM python:3.13-slim

ARG REQUIREMENTS_HASH=initial
RUN echo "Building with requirements hash: $REQUIREMENTS_HASH"

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-dev.txt ./

RUN pip install --no-cache-dir -r requirements-dev.txt

COPY ./tests/ ./tests/
COPY ./src/ ./
COPY ./test_data/ ./test_data/
COPY ./schemas/ ./schemas/
COPY pyproject.toml .

ENV PYTHONPATH=/app
ENV REST_API_URL=http://api:8000
