from _typeshed import Incomplete
from collections.abc import Generator
from jsonschema._utils import (
    ensure_list as ensure_list,
    equal as equal,
    extras_msg as extras_msg,
    find_additional_properties as find_additional_properties,
    find_evaluated_item_indexes_by_schema as find_evaluated_item_indexes_by_schema,
    find_evaluated_property_keys_by_schema as find_evaluated_property_keys_by_schema,
    uniq as uniq,
)
from jsonschema.exceptions import (
    FormatError as FormatError,
    ValidationError as ValidationError,
)

def patternProperties(
    validator, patternProperties, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def propertyNames(
    validator, propertyNames, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def additionalProperties(
    validator, aP, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def items(validator, items, instance, schema) -> Generator[Incomplete, Incomplete]: ...
def const(validator, const, instance, schema) -> Generator[Incomplete]: ...
def contains(validator, contains, instance, schema) -> Generator[Incomplete]: ...
def exclusiveMinimum(validator, minimum, instance, schema) -> Generator[Incomplete]: ...
def exclusiveMaximum(validator, maximum, instance, schema) -> Generator[Incomplete]: ...
def minimum(validator, minimum, instance, schema) -> Generator[Incomplete]: ...
def maximum(validator, maximum, instance, schema) -> Generator[Incomplete]: ...
def multipleOf(validator, dB, instance, schema) -> Generator[Incomplete]: ...
def minItems(validator, mI, instance, schema) -> Generator[Incomplete]: ...
def maxItems(validator, mI, instance, schema) -> Generator[Incomplete]: ...
def uniqueItems(validator, uI, instance, schema) -> Generator[Incomplete]: ...
def pattern(validator, patrn, instance, schema) -> Generator[Incomplete]: ...
def format(validator, format, instance, schema) -> Generator[Incomplete]: ...
def minLength(validator, mL, instance, schema) -> Generator[Incomplete]: ...
def maxLength(validator, mL, instance, schema) -> Generator[Incomplete]: ...
def dependentRequired(
    validator, dependentRequired, instance, schema
) -> Generator[Incomplete]: ...
def dependentSchemas(
    validator, dependentSchemas, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def enum(validator, enums, instance, schema) -> Generator[Incomplete]: ...
def ref(validator, ref, instance, schema) -> Generator[Incomplete, Incomplete]: ...
def dynamicRef(
    validator, dynamicRef, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def type(validator, types, instance, schema) -> Generator[Incomplete]: ...
def properties(
    validator, properties, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def required(validator, required, instance, schema) -> Generator[Incomplete]: ...
def minProperties(validator, mP, instance, schema) -> Generator[Incomplete]: ...
def maxProperties(validator, mP, instance, schema) -> Generator[Incomplete]: ...
def allOf(validator, allOf, instance, schema) -> Generator[Incomplete, Incomplete]: ...
def anyOf(validator, anyOf, instance, schema) -> Generator[Incomplete]: ...
def oneOf(validator, oneOf, instance, schema) -> Generator[Incomplete]: ...
def not_(validator, not_schema, instance, schema) -> Generator[Incomplete]: ...
def if_(
    validator, if_schema, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def unevaluatedItems(
    validator, unevaluatedItems, instance, schema
) -> Generator[Incomplete]: ...
def unevaluatedProperties(
    validator, unevaluatedProperties, instance, schema
) -> Generator[Incomplete]: ...
def prefixItems(
    validator, prefixItems, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
