from _typeshed import Incomplete
from collections.abc import Generator
from jsonschema.exceptions import ValidationError as ValidationError

def ignore_ref_siblings(schema): ...
def dependencies_draft3(
    validator, dependencies, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def dependencies_draft4_draft6_draft7(
    validator, dependencies, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def disallow_draft3(validator, disallow, instance, schema) -> Generator[Incomplete]: ...
def extends_draft3(
    validator, extends, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def items_draft3_draft4(
    validator, items, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def additionalItems(
    validator, aI, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def items_draft6_draft7_draft201909(
    validator, items, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def minimum_draft3_draft4(
    validator, minimum, instance, schema
) -> Generator[Incomplete]: ...
def maximum_draft3_draft4(
    validator, maximum, instance, schema
) -> Generator[Incomplete]: ...
def properties_draft3(
    validator, properties, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def type_draft3(validator, types, instance, schema) -> Generator[Incomplete]: ...
def contains_draft6_draft7(
    validator, contains, instance, schema
) -> Generator[Incomplete]: ...
def recursiveRef(
    validator, recursiveRef, instance, schema
) -> Generator[Incomplete, Incomplete]: ...
def find_evaluated_item_indexes_by_schema(validator, instance, schema): ...
def unevaluatedItems_draft2019(
    validator, unevaluatedItems, instance, schema
) -> Generator[Incomplete]: ...
def find_evaluated_property_keys_by_schema(validator, instance, schema): ...
def unevaluatedProperties_draft2019(
    validator, uP, instance, schema
) -> Generator[Incomplete]: ...
