$schema: https://json-schema.org/draft/2020-12/schema
$id: https://wikibase.org/schemas/s3-revision/4.0.0.json
title: S3 Revision Snapshot with Full Deduplication
description: Immutable entity revision snapshot stored in S3 with deduplication for terms, sitelinks (with badges), and statements.
type: object
required:
  - schema_version
  - revision_id
  - created_at
  - created_by
  - entity_type
  - entity
properties:
  schema_version:
    type: string
    pattern: ^\d+\.\d+\.\d+$
  revision_id:
    type: integer
    minimum: 0
  created_at:
    type: string
    format: date-time
  created_by:
    type: string
  entity_type:
    type: string
    enum:
      - item
      - property
      - lexeme
  redirects_to:
    type:
      - 'null'
      - string
    pattern: ^[A-Z]\d+$
    description: If this entity is a redirect, target entity ID it points to (e.g., 'Q42')
  content_hash:
    type: integer
    description: Rapidhash integer of entity data for deduplication
  edit_type:
    type: string
    description: Text classification of edit type
  is_semi_protected:
    type: boolean
    default: false
  is_locked:
    type: boolean
    default: false
  is_archived:
    type: boolean
    default: false
  is_dangling:
    type: boolean
    default: false
  is_mass_edit_protected:
    type: boolean
    default: false
  deleted:
    type: boolean
    default: false
  deletion_reason:
    type: string
  deleted_at:
    type: string
    format: date-time
  deleted_by:
    type: string
  labels_hashes:
    type: object
    description: Per-language hashes for individual label strings
    patternProperties:
      ^[a-z-]+$:
        type: integer
  descriptions_hashes:
    type: object
    description: Per-language hashes for individual description strings
    patternProperties:
      ^[a-z-]+$:
        type: integer
  aliases_hashes:
    type: object
    description: Per-language arrays of hashes for individual alias strings
    patternProperties:
      ^[a-z-]+$:
        type: array
        items:
          type: integer
   sitelinks:
     type: object
     description: Per-wiki sitelink data with title hash and badges
     patternProperties:
       ^[a-z-]+$:
         $ref: https://wikibase.org/schemas/s3-sitelink/1.0.0.json
  statements_hashes:
    type: object
    description: Hashes for statements grouped by property
    patternProperties:
      ^[A-Z]\d+$:
        type: array
        items:
          type: integer
  entity:
    type: object
    description: Minimal entity metadata (no claims, terms, or sitelinks)
    required:
      - id
      - type
    properties:
      id:
        type: string
        pattern: ^[A-Z]\d+$
      type:
        type: string