from _typeshed import Incomplete
from rdflib.term import URIRef
from typing import Any

__all__ = ["CSV2RDF"]

class NodeMaker:
    def range(self): ...
    def __call__(self, x: Any): ...

class NodeUri(NodeMaker):
    class_: URIRef | None
    prefix: Incomplete
    def __init__(self, prefix, class_) -> None: ...
    def __call__(self, x): ...
    def range(self): ...

class NodeLiteral(NodeMaker):
    f: Incomplete
    def __init__(self, f=None) -> None: ...

class NodeFloat(NodeLiteral):
    def __call__(self, x): ...
    def range(self): ...

class NodeInt(NodeLiteral):
    def __call__(self, x): ...
    def range(self): ...

class NodeBool(NodeLiteral):
    def __call__(self, x): ...
    def range(self): ...

class NodeReplace(NodeMaker):
    a: Incomplete
    b: Incomplete
    def __init__(self, a, b) -> None: ...
    def __call__(self, x): ...

class NodeDate(NodeLiteral):
    def __call__(self, x): ...
    def range(self): ...

class NodeSplit(NodeMaker):
    sep: Incomplete
    f: Incomplete
    def __init__(self, sep, f) -> None: ...
    def __call__(self, x): ...
    def range(self): ...

class CSV2RDF:
    CLASS: Incomplete
    BASE: Incomplete
    PROPBASE: Incomplete
    IDENT: tuple[str, ...] | str
    LABEL: Incomplete
    DEFINECLASS: bool
    SKIP: int
    DELIM: str
    DEFAULT: Incomplete
    COLUMNS: Incomplete
    PROPS: Incomplete
    OUT: Incomplete
    triples: int
    def __init__(self) -> None: ...
    def triple(self, s, p, o) -> None: ...
    def convert(self, csvreader) -> None: ...
