from _typeshed import Incomplete
from collections.abc import Generator
from rdflib import BNode as BNode, Graph as Graph

class IsomorphicTestableGraph(Graph):
    hash: Incomplete
    def __init__(self, **kargs) -> None: ...
    def internal_hash(self): ...
    def hashtriples(self) -> Generator[Incomplete]: ...
    def vhash(self, term, done: bool = False): ...
    def vhashtriples(self, term, done) -> Generator[Incomplete]: ...
    def vhashtriple(self, triple, term, done) -> Generator[Incomplete]: ...
    def __eq__(self, G): ...
    def __ne__(self, G): ...

def main() -> None: ...
