import codecs
import typing_extensions as te
from _typeshed import Incomplete
from rdflib.graph import Graph, _ObjectType, _PredicateType, _SubjectType
from rdflib.parser import InputSource, Parser
from rdflib.term import BNode as bNode, Literal, URIRef, URIRef as URI
from typing import Any, IO, Match, Pattern, TextIO

__all__ = [
    "unquote",
    "uriquote",
    "W3CNTriplesParser",
    "NTGraphSink",
    "NTParser",
    "DummySink",
]

class DummySink:
    length: int
    def __init__(self) -> None: ...
    def triple(self, s, p, o) -> None: ...

def unquote(s: str) -> str: ...
def uriquote(uri: str) -> str: ...

class W3CNTriplesParser:
    skolemize: bool
    sink: DummySink | NTGraphSink
    buffer: str | None
    file: TextIO | codecs.StreamReader | None
    line: str | None
    def __init__(
        self,
        sink: DummySink | NTGraphSink | None = None,
        bnode_context: _BNodeContextType | None = None,
    ) -> None: ...
    def parse(
        self,
        f: TextIO | IO[bytes] | codecs.StreamReader,
        bnode_context: _BNodeContextType | None = None,
        skolemize: bool = False,
    ) -> DummySink | NTGraphSink: ...
    def parsestring(self, s: bytes | bytearray | str, **kwargs) -> None: ...
    def readline(self) -> str | None: ...
    def parseline(self, bnode_context: _BNodeContextType | None = None) -> None: ...
    def peek(self, token: str) -> bool: ...
    def eat(self, pattern: Pattern[str]) -> Match[str]: ...
    def subject(self, bnode_context=None) -> bNode | URIRef: ...
    def predicate(self) -> bNode | URIRef: ...
    def object(
        self, bnode_context: _BNodeContextType | None = None
    ) -> URI | bNode | Literal: ...
    def uriref(self) -> te.Literal[False] | URI: ...
    def nodeid(
        self, bnode_context: _BNodeContextType | None = None
    ) -> te.Literal[False] | bNode | URI: ...
    def literal(self) -> te.Literal[False] | Literal: ...

class NTGraphSink:
    g: Incomplete
    def __init__(self, graph: Graph) -> None: ...
    def triple(self, s: _SubjectType, p: _PredicateType, o: _ObjectType) -> None: ...

class NTParser(Parser):
    @classmethod
    def parse(cls, source: InputSource, sink: Graph, **kwargs: Any) -> None: ...
