from .notation3 import RDFSink as RDFSink, SinkParser as SinkParser
from rdflib.graph import ConjunctiveGraph as ConjunctiveGraph, Graph as Graph
from rdflib.parser import InputSource as InputSource, Parser as Parser
from typing import Any, MutableSequence

def becauseSubGraph(*args, **kwargs) -> None: ...

class TrigSinkParser(SinkParser):
    def directiveOrStatement(self, argstr: str, h: int) -> int: ...
    def labelOrSubject(self, argstr: str, i: int, res: MutableSequence[Any]) -> int: ...
    def graph(self, argstr: str, i: int) -> int: ...

class TrigParser(Parser):
    def __init__(self) -> None: ...
    def parse(
        self, source: InputSource, graph: Graph, encoding: str = "utf-8"
    ) -> None: ...
