from _typeshed import Incomplete
from rdflib.graph import Graph
from rdflib.parser import InputSource, Parser
from rdflib.store import Store
from rdflib.term import BNode, Identifier
from typing import Any, NoReturn
from xml.sax import handler
from xml.sax.xmlreader import AttributesImpl, Locator, XMLReader

__all__ = ["create_parser", "TriXHandler", "TriXParser"]

class TriXHandler(handler.ContentHandler):
    lang: str | None
    datatype: str | None
    store: Incomplete
    preserve_bnode_ids: bool
    def __init__(self, store: Store) -> None: ...
    bnode: dict[str, BNode]
    graph: Graph | None
    triple: list[Identifier] | None
    state: int
    def reset(self) -> None: ...
    locator: Incomplete
    def setDocumentLocator(self, locator: Locator): ...
    def startDocument(self) -> None: ...
    def startPrefixMapping(self, prefix: str | None, namespace: str) -> None: ...
    def endPrefixMapping(self, prefix: str | None) -> None: ...
    chars: str
    def startElementNS(
        self, name: tuple[str | None, str], qname, attrs: AttributesImpl
    ) -> None: ...
    def endElementNS(self, name: tuple[str | None, str], qname) -> None: ...
    def get_bnode(self, label: str) -> BNode: ...
    def characters(self, content: str) -> None: ...
    def ignorableWhitespace(self, content) -> None: ...
    def processingInstruction(self, target, data) -> None: ...
    def error(self, message: str) -> NoReturn: ...

def create_parser(store: Store) -> XMLReader: ...

class TriXParser(Parser):
    def __init__(self) -> None: ...
    def parse(self, source: InputSource, sink: Graph, **args: Any) -> None: ...
