from _typeshed import Incomplete
from attrs import frozen
from collections.abc import Callable as Callable
from jsonschema.exceptions import UndefinedTypeCheck as UndefinedTypeCheck

def is_array(checker, instance): ...
def is_bool(checker, instance): ...
def is_integer(checker, instance): ...
def is_null(checker, instance): ...
def is_number(checker, instance): ...
def is_object(checker, instance): ...
def is_string(checker, instance): ...
def is_any(checker, instance): ...
@frozen(repr=False)
class TypeChecker:
    def is_type(self, instance, type: str) -> bool: ...
    def redefine(self, type: str, fn) -> TypeChecker: ...
    def redefine_many(self, definitions=()) -> TypeChecker: ...
    def remove(self, *types) -> TypeChecker: ...

draft3_type_checker: Incomplete
draft4_type_checker: Incomplete
draft6_type_checker: Incomplete
draft7_type_checker = draft6_type_checker
draft201909_type_checker = draft7_type_checker
draft202012_type_checker = draft201909_type_checker
