from _typeshed import Incomplete
from collections.abc import Generator, MutableMapping

class URIDict(MutableMapping):
    def normalize(self, uri): ...
    store: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, uri): ...
    def __setitem__(self, uri, value) -> None: ...
    def __delitem__(self, uri) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...

class Unset: ...

def format_as_index(container, indices): ...
def find_additional_properties(instance, schema) -> Generator[Incomplete]: ...
def extras_msg(extras): ...
def ensure_list(thing): ...
def equal(one, two): ...
def unbool(element, true=..., false=...): ...
def uniq(container): ...
def find_evaluated_item_indexes_by_schema(validator, instance, schema): ...
def find_evaluated_property_keys_by_schema(validator, instance, schema): ...
def is_valid(errs_it): ...
