from _typeshed import Incomplete
from attrs import define
from jsonschema.exceptions import SchemaError as SchemaError
from jsonschema.validators import validator_for as validator_for

class _CannotLoadFile(Exception): ...

@define
class _Outputter:
    @classmethod
    def from_arguments(cls, arguments, stdout, stderr): ...
    def load(self, path): ...
    def filenotfound_error(self, **kwargs) -> None: ...
    def parsing_error(self, **kwargs) -> None: ...
    def validation_error(self, **kwargs) -> None: ...
    def validation_success(self, **kwargs) -> None: ...

@define
class _PrettyFormatter:
    def filenotfound_error(self, path, exc_info): ...
    def parsing_error(self, path, exc_info): ...
    def validation_error(self, instance_path, error): ...
    def validation_success(self, instance_path): ...

@define
class _PlainFormatter:
    def filenotfound_error(self, path, exc_info): ...
    def parsing_error(self, path, exc_info): ...
    def validation_error(self, instance_path, error): ...
    def validation_success(self, instance_path): ...

parser: Incomplete

def parse_args(args): ...
def main(args=...) -> None: ...
def run(arguments, stdout=..., stderr=..., stdin=...): ...
