from _typeshed import Incomplete
from rdflib.graph import Graph
from rdflib.plugins.serializers.turtle import TurtleSerializer

__all__ = ["N3Serializer"]

class N3Serializer(TurtleSerializer):
    short_name: str
    parent: Incomplete
    def __init__(self, store: Graph, parent=None) -> None: ...
    def reset(self) -> None: ...
    def endDocument(self) -> None: ...
    def indent(self, modifier: int = 0): ...
    def preprocessTriple(self, triple) -> None: ...
    def getQName(self, uri, gen_prefix: bool = True): ...
    def statement(self, subject): ...
    def path(self, node, position, newline: bool = False) -> None: ...
    def s_clause(self, subject): ...
    def p_clause(self, node, position): ...
