#!/bin/bash
cd "$(dirname "$0")/../.."
set -e

ID_WORKER_ENABLED=${ID_WORKER_ENABLED:-false}
JSON_WORKER_ENABLED=${JSON_WORKER_ENABLED:-false}
TTL_WORKER_ENABLED=${TTL_WORKER_ENABLED:-false}
STATS_WORKER_ENABLED=${STATS_WORKER_ENABLED:-false}
PURGE_WORKER_ENABLED=${PURGE_WORKER_ENABLED:-false}

echo "Exporting Poetry dependencies to requirements files..."
echo ""

mkdir -p var

POETRY="poetry"

step() {
    printf "[%s] %s\n" "$1" "$2"
}

add_warning() {
    local file=$1
    local warning="# WARNING: This file is auto-generated by ./scripts/shell/export-requirements.sh
# Do NOT edit this file directly - changes will be overwritten!
# To modify dependencies, edit pyproject.toml or the export script instead.
# Generated files are stored in var/ directory.
#"
    sed -i "1i\\$warning" "$file"
}

step "main" "Exporting main requirements.txt"
$POETRY export --format requirements.txt --output var/requirements.txt --without-hashes
add_warning var/requirements.txt

step "dev" "Exporting requirements-dev.txt"
$POETRY export --format requirements.txt --output var/requirements-dev.txt --without-hashes --with dev
add_warning var/requirements-dev.txt

step "api" "Exporting API requirements"
$POETRY export --format requirements.txt --output var/requirements-api.txt --without-hashes --only=api
add_warning var/requirements-api.txt

step "create-buckets" "Exporting create-buckets requirements"
$POETRY export --format requirements.txt --output var/requirements-create-buckets.txt --without-hashes --only=create-buckets
add_warning var/requirements-create-buckets.txt

step "create-tables" "Exporting create-tables requirements"
$POETRY export --format requirements.txt --output var/requirements-create-tables.txt --without-hashes --only=create-tables
add_warning var/requirements-create-tables.txt

step "create-topics" "Exporting create-topics requirements"
$POETRY export --format requirements.txt --output var/requirements-create-topics.txt --without-hashes --only=create-topics
add_warning var/requirements-create-topics.txt

if [ "$ID_WORKER_ENABLED" = "true" ]; then
    step "idworker" "Exporting idworker requirements"
    $POETRY export --format requirements.txt --output var/requirements-idworker.txt --without-hashes --only=idworker
    add_warning var/requirements-idworker.txt
fi

if [ "$STATS_WORKER_ENABLED" = "true" ]; then
    step "stats-worker" "Exporting stats-worker requirements"
    $POETRY export --format requirements.txt --output var/requirements-stats-worker.txt --without-hashes --only=stats-worker
    add_warning var/requirements-stats-worker.txt
fi

if [ "$JSON_WORKER_ENABLED" = "true" ]; then
    step "json-worker" "Exporting json-worker requirements"
    $POETRY export --format requirements.txt --output var/requirements-json-worker.txt --without-hashes --only=json-worker
    add_warning var/requirements-json-worker.txt
fi

if [ "$TTL_WORKER_ENABLED" = "true" ]; then
    step "ttl-worker" "Exporting ttl-worker requirements"
    $POETRY export --format requirements.txt --output var/requirements-ttl-worker.txt --without-hashes --only=ttl-worker
    add_warning var/requirements-ttl-worker.txt
fi

if [ "$PURGE_WORKER_ENABLED" = "true" ]; then
    step "purge-worker" "Exporting purge-worker requirements"
    $POETRY export --format requirements.txt --output var/requirements-purge-worker.txt --without-hashes --only=purge-worker
    add_warning var/requirements-purge-worker.txt
fi

if [ "$INCREMENTAL_RDF_ENABLED" = "true" ]; then
    step "incremental-rdf-worker" "Exporting incremental-rdf-worker requirements"
    $POETRY export --format requirements.txt --output var/requirements-incremental-rdf-worker.txt --without-hashes --only=incremental-rdf-worker
    add_warning var/requirements-incremental-rdf-worker.txt
fi

echo ""
echo "✓ Requirements files updated successfully in var/"