#!/bin/bash
cd "$(dirname "$0")/../.."
set -e

echo "Exporting Poetry dependencies to requirements files..."

POETRY="poetry"

# Warning comment to prepend to generated files
WARNING="# WARNING: This file is auto-generated by ./scripts/shell/export-requirements.sh
# Do NOT edit this file directly - changes will be overwritten!
# To modify dependencies, edit pyproject.toml or the export script instead.
#"

export_requirements() {
    local output=$1
    shift
    $POETRY export --format requirements.txt --output "$output" --without-hashes "$@"
    # Prepend warning comment
    sed -i "1i\\$WARNING" "$output"
}

$POETRY export --format requirements.txt --output requirements.txt --without-hashes
sed -i "1i\\$WARNING" requirements.txt

$POETRY export --format requirements.txt --output requirements-dev.txt --without-hashes --with dev
sed -i "1i\\$WARNING" requirements-dev.txt

export_requirements requirements-api.txt --with api
export_requirements requirements-idworker.txt --with idworker
export_requirements requirements-stats-worker.txt --with stats-worker
export_requirements requirements-json-worker.txt --with json-worker
export_requirements requirements-ttl-worker.txt --with ttl-worker
export_requirements docker/containers/requirements-purge-worker.txt --with purge-worker

echo "Requirements files updated successfully"