from _typeshed import Incomplete
from collections.abc import Generator
from rdflib.graph import Graph as Graph
from rdflib.store import Store as Store

NATIVE_REGEX: int
PYTHON_REGEX: int

class REGEXTerm(str):
    compiledExpr: Incomplete
    def __init__(self, expr) -> None: ...
    def __reduce__(self): ...

def regexCompareQuad(quad, regexQuad): ...

class REGEXMatching(Store):
    storage: Incomplete
    context_aware: Incomplete
    formula_aware: Incomplete
    transaction_aware: Incomplete
    def __init__(self, storage) -> None: ...
    def open(self, configuration, create: bool = True): ...
    def close(self, commit_pending_transaction: bool = False) -> None: ...
    def destroy(self, configuration) -> None: ...
    def add(self, triple, context, quoted: bool = False) -> None: ...
    def remove(self, triple, context=None) -> None: ...
    def triples(self, triple, context=None) -> Generator[Incomplete]: ...
    def __len__(self, context=None) -> int: ...
    def contexts(self, triple=None) -> Generator[Incomplete]: ...
    def remove_context(self, identifier) -> None: ...
    def bind(self, prefix, namespace, override: bool = True) -> None: ...
    def prefix(self, namespace): ...
    def namespace(self, prefix): ...
    def namespaces(self): ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
