from collections.abc import Callable as Callable, Collection, Iterable, Iterator
from typing import Any, Generic, TypeVar

T = TypeVar("T")

class SortedSet(Collection[T], Generic[T]):
    def __init__(
        self, iterable: Iterable[T] | None = None, key: Callable[[T], Any] | None = None
    ) -> None: ...
    def first(self) -> T | None: ...
    def last(self) -> T | None: ...
    def pop_last(self) -> T: ...
    def add(self, value: T) -> None: ...
    def remove(self, value: T) -> None: ...
    def __contains__(self, value: Any) -> bool: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...
