@startuml Detailed Worker Components

title Wikibase Backend - Detailed Worker Components

package "Workers" as Workers #LightYellow {
    "BacklinkStatistics" as BacklinkStatisticsWorker
    "BaseStats" as BaseStatsWorker
    "BucketHealthCheckResult" as BucketHealthCheckResult
    "BucketSetupResult" as BucketSetupResult
    "CanonicalizationMethod" as CanonicalizationMethod
    "ChangedProperties" as ChangedProperties
    "CreateBuckets" as CreateBuckets
    "CreateTables" as CreateTables
    "DumpMetadata" as DumpMetadata
    "EntityDiffRequest" as EntityDiffRequest
    "EntityDiffResponse" as EntityDiffResponse
    "EntityDiff" as EntityDiffWorker
    "EntityDumpRecord" as EntityDumpRecord
    "EventConfig" as EventConfig
    "GeneralStats" as GeneralStatsWorker
    "IdGenerator" as IdGeneratorWorker
    "IncrementalRDF" as IncrementalRDFWorker
    "JsonDump" as JsonDumpWorker
    "NotificationCleanup" as NotificationCleanupWorker
    "NotificationData" as NotificationData
    "RDFCanonicalizer" as RDFCanonicalizer
    "RDFChangeEvent" as RDFChangeEvent
    "RDFChangeEventBuilder" as RDFChangeEventBuilder
    "RDFDataField" as RDFDataField
    "RDFSerializer" as RDFSerializer
    "TableHealthCheckResult" as TableHealthCheckResult
    "TableSetupResult" as TableSetupResult
    "TtlDump" as TtlDumpWorker
    "UserStats" as UserStatsWorker
    "Vitess" as VitessWorker
    "WatchlistConsumer" as WatchlistConsumerWorker
}

@enduml