@startuml Detailed Model Components

title Wikibase Backend - Detailed Model Components

package "Models" as Models #LightCyan {
    "AliasValue" as AliasValue
    "Aliases" as AliasesResponse
    "Backlink" as BacklinkResponse
    "BacklinkStatisticsData" as BacklinkStatisticsData
    "BacklinkStatistics" as BacklinkStatisticsResponse
    "Backlinks" as BacklinksResponse
    "BatchEndorsementStats" as BatchEndorsementStatsResponse
    "CleanupOrphaned" as CleanupOrphanedResponse
    "DeduplicationStats" as DeduplicationStatsResponse
    "Description" as DescriptionResponse
    "DescriptionValue" as DescriptionValue
    "Descriptions" as DescriptionsResponse
    "EndorsementList" as EndorsementListResponse
    "Endorsement" as EndorsementResponse
    "EndorsementStats" as EndorsementStatsResponse
    "Entities" as EntitiesResponse
    "EntityAliases" as EntityAliasesResponse
    "EntityChange" as EntityChange
    "EntityDelete" as EntityDeleteResponse
    "EntityDescriptions" as EntityDescriptionsResponse
    "EntityHistoryEntry" as EntityHistoryEntry
    "EntityJsonImport" as EntityJsonImportResponse
    "EntityJson" as EntityJsonResponse
    "EntityLabels" as EntityLabelsResponse
    "EntityListItem" as EntityListItem
    "EntityListItemWithEditType" as EntityListItemWithEditType
    "EntityList" as EntityListResponse
    "EntityListing" as EntityListing
    "EntityMetadataBatch" as EntityMetadataBatchResponse
    "EntityMetadata" as EntityMetadataResponse
    "EntityRedirect" as EntityRedirectResponse
    "Entity" as EntityResponse
    "EntityRevert" as EntityRevertResponse
    "EntitySitelinks" as EntitySitelinksResponse
    "EntityStatements" as EntityStatementsResponse
    "FormRepresentation" as FormRepresentationResponse
    "FormRepresentations" as FormRepresentationsResponse
    "Form" as FormResponse
    "Forms" as FormsResponse
    "FullRevision" as FullRevisionResponse
    "GeneralStatsData" as GeneralStatsData
    "GeneralStats" as GeneralStatsResponse
    "HealthCheck" as HealthCheckResponse
    "Health" as HealthResponse
    "Id" as IdResponse
    "Label" as LabelResponse
    "LabelValue" as LabelValue
    "Labels" as LabelsResponse
    "Lemma" as LemmaResponse
    "Lemmas" as LemmasResponse
    "Message" as MessageResponse
    "MetadataContent" as MetadataContent
    "MetadataData" as MetadataData
    "MetadataLoad" as MetadataLoadResponse
    "MostUsedStatements" as MostUsedStatementsResponse
    "Notification" as NotificationResponse
    "Properties" as PropertiesResponse
    "PropertyCounts" as PropertyCountsResponse
    "PropertyHashes" as PropertyHashesResponse
    "PropertyList" as PropertyListResponse
    "PropertyRecalculationResult" as PropertyRecalculationResult
    "Protection" as ProtectionResponse
    "Qualifier" as QualifierResponse
    "RDFChangeEvent" as RDFChangeEvent
    "RangeStatus" as RangeStatus
    "RangeStatuses" as RangeStatuses
    "ReconstructedSnakValue" as ReconstructedSnakValue
    "RedirectBatch" as RedirectBatchResponse
    "Reference" as ReferenceResponse
    "RepresentationData" as RepresentationData
    "RevisionIdResult" as RevisionIdResult
    "RevisionMetadata" as RevisionMetadataResponse
    "RevisionRead" as RevisionReadResponse
    "RevisionResult" as RevisionResult
    "SenseGloss" as SenseGlossResponse
    "SenseGlosses" as SenseGlossesResponse
    "Sense" as SenseResponse
    "Senses" as SensesResponse
    "SerializableQualifierValue" as SerializableQualifierValue
    "SingleEndorsementStats" as SingleEndorsementStatsResponse
    "SitelinkValue" as SitelinkValue
    "Sitelinks" as SitelinksResponse
    "Snak" as SnakResponse
    "StatementBatch" as StatementBatchResponse
    "StatementEndorsement" as StatementEndorsementResponse
    "StatementEndorsementStats" as StatementEndorsementStats
    "StatementHashResult" as StatementHashResult
    "Statement" as StatementResponse
    "StatementsHash" as StatementsHashResponse
    "Statements" as StatementsResponse
    "TermsByType" as TermsByType
    "TermsPerLanguage" as TermsPerLanguage
    "Terms" as TermsResponse
    "ThankItem" as ThankItemResponse
    "Thank" as ThankResponse
    "ThanksList" as ThanksListResponse
    "TopEntityByBacklinks" as TopEntityByBacklinks
    "Turtle" as TurtleResponse
    "UserActivityItem" as UserActivityItemResponse
    "UserActivity" as UserActivityResponse
    "UserCreate" as UserCreateResponse
    "UserPreferences" as UserPreferencesResponse
    "User" as UserResponse
    "UserStatsData" as UserStatsData
    "UserStats" as UserStatsResponse
    "WatchCounts" as WatchCounts
    "WatchlistEntry" as WatchlistEntryResponse
    "Watchlist" as WatchlistResponse
    "WatchlistToggle" as WatchlistToggleResponse
    "WikibasePredicates" as WikibasePredicatesResponse
    "WorkerHealthCheck" as WorkerHealthCheckResponse
}

@enduml