import _cython_3_2_3
import aiokafka.codec as codecs
from _typeshed import Incomplete
from aiokafka.codec import (
    gzip_decode as gzip_decode,
    gzip_encode as gzip_encode,
    lz4_decode as lz4_decode,
    lz4_encode as lz4_encode,
    snappy_decode as snappy_decode,
    snappy_encode as snappy_encode,
    zstd_decode as zstd_decode,
    zstd_encode as zstd_encode,
)
from aiokafka.errors import (
    CorruptRecordException as CorruptRecordException,
    UnsupportedCodecError as UnsupportedCodecError,
)
from typing import ClassVar

__reduce_cython__: _cython_3_2_3.cython_function_or_method
__setstate_cython__: _cython_3_2_3.cython_function_or_method
__test__: dict

class DefaultRecord:
    checksum: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    headers: Incomplete
    key: Incomplete
    offset: Incomplete
    timestamp: Incomplete
    timestamp_type: Incomplete
    value: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...

class DefaultRecordBatch:
    CODEC_GZIP: ClassVar[int] = ...
    CODEC_LZ4: ClassVar[int] = ...
    CODEC_MASK: ClassVar[int] = ...
    CODEC_NONE: ClassVar[int] = ...
    CODEC_SNAPPY: ClassVar[int] = ...
    CODEC_ZSTD: ClassVar[int] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    attributes: Incomplete
    base_offset: Incomplete
    base_sequence: Incomplete
    compression_type: Incomplete
    crc: Incomplete
    first_timestamp: Incomplete
    is_control_batch: Incomplete
    is_transactional: Incomplete
    last_offset_delta: Incomplete
    magic: Incomplete
    max_timestamp: Incomplete
    next_offset: Incomplete
    producer_epoch: Incomplete
    producer_id: Incomplete
    timestamp_type: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def validate_crc(self, *args, **kwargs): ...
    def __iter__(self): ...
    def __next__(self): ...
    def __reduce__(self): ...

class DefaultRecordBatchBuilder:
    estimate_size_in_bytes: ClassVar[method] = ...
    size_of: ClassVar[method] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    base_sequence: Incomplete
    producer_epoch: Incomplete
    producer_id: Incomplete
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def build(self, *args, **kwargs): ...
    def set_producer_state(self, *args, **kwargs): ...
    def size(self, *args, **kwargs): ...
    def size_in_bytes(self, *args, **kwargs): ...
    def __reduce__(self): ...

class DefaultRecordMetadata:
    crc: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    offset: Incomplete
    size: Incomplete
    timestamp: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...
