import _cython_3_2_3
import aiokafka.codec as codecs
from _typeshed import Incomplete
from aiokafka.codec import (
    gzip_decode as gzip_decode,
    gzip_encode as gzip_encode,
    lz4_decode as lz4_decode,
    lz4_encode as lz4_encode,
    snappy_decode as snappy_decode,
    snappy_encode as snappy_encode,
)
from aiokafka.errors import (
    CorruptRecordException as CorruptRecordException,
    UnsupportedCodecError as UnsupportedCodecError,
)
from typing import ClassVar

__reduce_cython__: _cython_3_2_3.cython_function_or_method
__setstate_cython__: _cython_3_2_3.cython_function_or_method
__test__: dict

class LegacyRecord:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    checksum: Incomplete
    headers: Incomplete
    key: Incomplete
    offset: Incomplete
    timestamp: Incomplete
    timestamp_type: Incomplete
    value: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...

class LegacyRecordBatch:
    CODEC_GZIP: ClassVar[int] = ...
    CODEC_LZ4: ClassVar[int] = ...
    CODEC_MASK: ClassVar[int] = ...
    CODEC_SNAPPY: ClassVar[int] = ...
    RECORD_OVERHEAD_V0: ClassVar[int] = ...
    RECORD_OVERHEAD_V1: ClassVar[int] = ...
    is_control_batch: ClassVar[bool] = ...
    is_transactional: ClassVar[bool] = ...
    producer_id: ClassVar[None] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    next_offset: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def validate_crc(self, *args, **kwargs): ...
    def __iter__(self): ...
    def __reduce__(self): ...

class LegacyRecordBatchBuilder:
    CODEC_GZIP: ClassVar[int] = ...
    CODEC_LZ4: ClassVar[int] = ...
    CODEC_MASK: ClassVar[int] = ...
    CODEC_SNAPPY: ClassVar[int] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def append(self, *args, **kwargs): ...
    def build(self, *args, **kwargs): ...
    @staticmethod
    def record_overhead(*args, **kwargs): ...
    def size(self, *args, **kwargs): ...
    def size_in_bytes(self, *args, **kwargs): ...
    def __reduce__(self): ...

class LegacyRecordMetadata:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    crc: Incomplete
    offset: Incomplete
    size: Incomplete
    timestamp: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...
