from aiokafka.errors import CorruptRecordException as CorruptRecordException
from typing import ClassVar

__test__: dict

class MemoryRecords:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def has_next(self, *args, **kwargs): ...
    def next_batch(self, *args, **kwargs): ...
    def size_in_bytes(self, *args, **kwargs): ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...
