from _typeshed import Incomplete
from aiokafka.client import (
    ConnectionGroup as ConnectionGroup,
    CoordinationType as CoordinationType,
)
from aiokafka.errors import (
    ConcurrentTransactions as ConcurrentTransactions,
    CoordinatorLoadInProgressError as CoordinatorLoadInProgressError,
    CoordinatorNotAvailableError as CoordinatorNotAvailableError,
    DuplicateSequenceNumber as DuplicateSequenceNumber,
    GroupAuthorizationFailedError as GroupAuthorizationFailedError,
    IncompatibleBrokerVersion as IncompatibleBrokerVersion,
    InvalidProducerEpoch as InvalidProducerEpoch,
    InvalidProducerIdMapping as InvalidProducerIdMapping,
    InvalidTxnState as InvalidTxnState,
    KafkaError as KafkaError,
    NotCoordinatorError as NotCoordinatorError,
    OperationNotAttempted as OperationNotAttempted,
    OutOfOrderSequenceNumber as OutOfOrderSequenceNumber,
    ProducerFenced as ProducerFenced,
    RequestTimedOutError as RequestTimedOutError,
    TopicAuthorizationFailedError as TopicAuthorizationFailedError,
    TransactionalIdAuthorizationFailed as TransactionalIdAuthorizationFailed,
    UnknownTopicOrPartitionError as UnknownTopicOrPartitionError,
)
from aiokafka.protocol.produce import ProduceRequest as ProduceRequest
from aiokafka.protocol.transaction import (
    AddOffsetsToTxnRequest as AddOffsetsToTxnRequest,
    AddPartitionsToTxnRequest as AddPartitionsToTxnRequest,
    EndTxnRequest as EndTxnRequest,
    InitProducerIdRequest as InitProducerIdRequest,
    TxnOffsetCommitRequest as TxnOffsetCommitRequest,
)
from aiokafka.structs import TopicPartition as TopicPartition
from aiokafka.util import create_task as create_task

log: Incomplete
BACKOFF_OVERRIDE: float

class Sender:
    client: Incomplete
    def __init__(
        self,
        client,
        *,
        acks,
        txn_manager,
        message_accumulator,
        retry_backoff_ms,
        linger_ms,
        request_timeout_ms,
    ) -> None: ...
    async def start(self) -> None: ...
    @property
    def sender_task(self): ...
    async def close(self) -> None: ...

class BaseHandler:
    group: Incomplete
    def __init__(self, sender) -> None: ...
    async def do(self, node_id): ...
    def create_request(self) -> None: ...
    def handle_response(self, response) -> None: ...
    def handle_error(self) -> None: ...

class InitPIDHandler(BaseHandler):
    def create_request(self): ...
    def handle_response(self, resp): ...
    def handle_error(self): ...

class AddPartitionsToTxnHandler(BaseHandler):
    group: Incomplete
    def __init__(self, sender, topic_partitions) -> None: ...
    def create_request(self): ...
    def handle_response(self, resp): ...
    def handle_error(self): ...

class AddOffsetsToTxnHandler(BaseHandler):
    group: Incomplete
    def __init__(self, sender, group_id) -> None: ...
    def create_request(self): ...
    def handle_response(self, resp): ...
    def handle_error(self): ...

class TxnOffsetCommitHandler(BaseHandler):
    group: Incomplete
    def __init__(self, sender, offsets, group_id) -> None: ...
    def create_request(self): ...
    def handle_response(self, resp): ...
    def handle_error(self): ...

class EndTxnHandler(BaseHandler):
    group: Incomplete
    def __init__(self, sender, commit_result) -> None: ...
    def create_request(self): ...
    def handle_response(self, resp): ...
    def handle_error(self): ...

class SendProduceReqHandler(BaseHandler):
    def __init__(self, sender, batches) -> None: ...
    def create_request(self): ...
    async def do(self, node_id) -> None: ...
    def handle_response(self, response) -> None: ...
    def handle_error(self): ...
