from _typeshed import Incomplete
from aiokafka.structs import TopicPartition as TopicPartition
from aiokafka.util import create_future as create_future
from enum import Enum, IntEnum
from typing import NamedTuple

class PidAndEpoch(NamedTuple):
    pid: Incomplete
    epoch: Incomplete

NO_PRODUCER_ID: int
NO_PRODUCER_EPOCH: int

class SubscriptionType(Enum):
    NONE = 1
    AUTO_TOPICS = 2
    AUTO_PATTERN = 3
    USER_ASSIGNED = 4

class TransactionResult(IntEnum):
    ABORT = 0
    COMMIT = 1

class TransactionState(Enum):
    UNINITIALIZED = 1
    READY = 2
    IN_TRANSACTION = 3
    COMMITTING_TRANSACTION = 4
    ABORTING_TRANSACTION = 5
    ABORTABLE_ERROR = 6
    FATAL_ERROR = 7
    @classmethod
    def is_transition_valid(cls, source, target): ...

class TransactionManager:
    transactional_id: Incomplete
    transaction_timeout_ms: Incomplete
    state: Incomplete
    def __init__(self, transactional_id, transaction_timeout_ms) -> None: ...
    def set_pid_and_epoch(self, pid: int, epoch: int): ...
    def has_pid(self): ...
    async def wait_for_pid(self) -> None: ...
    def sequence_number(self, tp: TopicPartition): ...
    def increment_sequence_number(self, tp: TopicPartition, increment: int): ...
    @property
    def producer_id(self): ...
    @property
    def producer_epoch(self): ...
    def begin_transaction(self) -> None: ...
    def committing_transaction(self) -> None: ...
    def aborting_transaction(self) -> None: ...
    def complete_transaction(self) -> None: ...
    def error_transaction(self, exc) -> None: ...
    def fatal_error(self, exc) -> None: ...
    def maybe_add_partition_to_txn(self, tp: TopicPartition): ...
    def add_offsets_to_txn(self, offsets, group_id): ...
    def is_in_transaction(self): ...
    def partitions_to_add(self): ...
    def consumer_group_to_add(self): ...
    def offsets_to_commit(self): ...
    def partition_added(self, tp: TopicPartition): ...
    def consumer_group_added(self, group_id) -> None: ...
    def offset_committed(self, tp, offset, group_id) -> None: ...
    @property
    def txn_partitions(self): ...
    def needs_transaction_commit(self): ...
    def is_empty_transaction(self): ...
    def is_fatal_error(self): ...
    def wait_for_transaction_end(self): ...
    def notify_task_waiter(self) -> None: ...
    def make_task_waiter(self): ...
