$schema: https://json-schema.org/draft/2020-12/schema
$id: https://wikibase.org/schemas/s3-snak/1.0.0.json
title: S3 Snak Snapshot
description: Immutable snak snapshot stored in S3 for deduplication of property-value assertions across statements, qualifiers, and references.
type: object
required:
- schema_version
- snak
- created_at
properties:
  schema_version:
    type: string
    pattern: ^\d+\.\d+\.\d+$
    description: Schema version (MAJOR.MINOR.PATCH)
  snak:
    type: object
    description: The full snak object.
    required:
      - snaktype
      - property
      - datatype
    properties:
      snaktype:
        type: string
        enum:
          - value
          - somevalue
          - novalue
        description: 'Type of snak: value, somevalue, or novalue.'
      property:
        type: string
        description: Wikidata property identifier (e.g., P31, P569).
      datatype:
        type: string
        description: Data type of the property value.
      hash:
        type: string
        description: Hash of the datavalue.
      datavalue:
        description: The value data.
  created_at:
    type: string
    format: date-time
    description: ISO 8601 timestamp when this snak was created.
    examples:
    - '2026-01-05T10:00:00Z'