from _typeshed import Incomplete
from aiokafka.conn import collect_hosts as collect_hosts
from aiokafka.structs import (
    BrokerMetadata as BrokerMetadata,
    PartitionMetadata as PartitionMetadata,
    TopicPartition as TopicPartition,
)

log: Incomplete

class ClusterMetadata:
    DEFAULT_CONFIG: Incomplete
    need_all_topic_metadata: bool
    unauthorized_topics: Incomplete
    internal_topics: Incomplete
    controller: Incomplete
    config: Incomplete
    def __init__(self, **configs) -> None: ...
    def is_bootstrap(self, node_id): ...
    def brokers(self): ...
    def broker_metadata(self, broker_id): ...
    def partitions_for_topic(self, topic: str) -> set[int] | None: ...
    def available_partitions_for_topic(self, topic): ...
    def leader_for_partition(self, partition): ...
    def partitions_for_broker(self, broker_id): ...
    def coordinator_for_group(self, group): ...
    def request_update(self): ...
    def topics(self, exclude_internal_topics: bool = True): ...
    def failed_update(self, exception) -> None: ...
    def update_metadata(self, metadata) -> None: ...
    def add_listener(self, listener) -> None: ...
    def remove_listener(self, listener) -> None: ...
    def add_group_coordinator(self, group, response): ...
    def with_partitions(self, partitions_to_add): ...
    def coordinator_metadata(self, node_id): ...
    def add_coordinator(self, node_id, host, port, rack=None, *, purpose) -> None: ...
