from typing_extensions import Buffer

def has_gzip() -> bool: ...
def has_snappy() -> bool: ...
def has_zstd() -> bool: ...
def has_lz4() -> bool: ...
def gzip_encode(payload: Buffer, compresslevel: int | None = None) -> bytes: ...
def gzip_decode(payload: Buffer) -> bytes: ...
def snappy_encode(
    payload: Buffer, xerial_compatible: bool = True, xerial_blocksize: int = ...
) -> bytes: ...
def snappy_decode(payload: Buffer) -> bytes: ...
def lz4_encode(payload: Buffer, level: int = 9) -> bytes: ...
def lz4_decode(payload: Buffer) -> bytes: ...
def zstd_encode(payload: Buffer, level: int | None = None) -> bytes: ...
def zstd_decode(payload: Buffer) -> bytes: ...
