import asyncio
from _typeshed import Incomplete
from collections.abc import Generator
from enum import IntEnum

__all__ = ["AIOKafkaConnection", "create_conn"]

class CloseReason(IntEnum):
    CONNECTION_BROKEN = 0
    CONNECTION_TIMEOUT = 1
    OUT_OF_SYNC = 2
    IDLE_DROP = 3
    SHUTDOWN = 4
    AUTH_FAILURE = 5

async def create_conn(
    host,
    port,
    *,
    client_id: str = "aiokafka",
    request_timeout_ms: int = 40000,
    ssl_context=None,
    security_protocol: str = "PLAINTEXT",
    max_idle_ms=None,
    on_close=None,
    sasl_mechanism=None,
    sasl_plain_username=None,
    sasl_plain_password=None,
    sasl_kerberos_service_name: str = "kafka",
    sasl_kerberos_domain_name=None,
    sasl_oauth_token_provider=None,
): ...

class AIOKafkaProtocol(asyncio.StreamReaderProtocol):
    def __init__(self, closed_fut, *args, loop, **kw) -> None: ...
    def connection_lost(self, exc) -> None: ...

class AIOKafkaConnection:
    def __init__(
        self,
        host,
        port,
        *,
        client_id: str = "aiokafka",
        request_timeout_ms: int = 40000,
        ssl_context=None,
        security_protocol: str = "PLAINTEXT",
        max_idle_ms=None,
        on_close=None,
        sasl_mechanism=None,
        sasl_plain_password=None,
        sasl_plain_username=None,
        sasl_kerberos_service_name: str = "kafka",
        sasl_kerberos_domain_name=None,
        sasl_oauth_token_provider=None,
    ) -> None: ...
    def __del__(self, _warnings=...) -> None: ...
    async def connect(self): ...
    def authenticator_plain(self): ...
    def authenticator_gssapi(self): ...
    def authenticator_scram(self): ...
    def authenticator_oauth(self): ...
    @property
    def sasl_principal(self): ...
    @property
    def host(self): ...
    @property
    def port(self): ...
    def send(self, request, expect_response: bool = True): ...
    def connected(self): ...
    def close(self, reason=None, exc=None): ...

class BaseSaslAuthenticator:
    def step(self, payload): ...

class SaslPlainAuthenticator(BaseSaslAuthenticator):
    def __init__(self, *, loop, sasl_plain_password, sasl_plain_username) -> None: ...
    def authenticator_plain(self) -> Generator[Incomplete, Incomplete]: ...

class SaslGSSAPIAuthenticator(BaseSaslAuthenticator):
    def __init__(self, *, loop, principal) -> None: ...
    def authenticator_gssapi(self) -> Generator[Incomplete, Incomplete]: ...

class ScramAuthenticator(BaseSaslAuthenticator):
    MECHANISMS: Incomplete
    def __init__(
        self, *, loop, sasl_plain_password, sasl_plain_username, sasl_mechanism
    ) -> None: ...
    def first_message(self): ...
    def process_server_first_message(self, server_first) -> None: ...
    def final_message(self): ...
    def process_server_final_message(self, server_final) -> None: ...
    def authenticator_scram(self) -> Generator[Incomplete, Incomplete]: ...
    def hmac(self, key, msg): ...
    def create_salted_password(self, salt, iterations) -> None: ...

class OAuthAuthenticator(BaseSaslAuthenticator):
    def __init__(self, *, sasl_oauth_token_provider) -> None: ...
    async def step(self, payload): ...
