from .turtle import RecursiveSerializer
from _typeshed import Incomplete
from rdflib.graph import _TripleType
from typing import Any, IO

__all__ = ["LongTurtleSerializer"]

class LongTurtleSerializer(RecursiveSerializer):
    short_name: str
    indentString: str
    keywords: Incomplete
    stream: Incomplete
    def __init__(self, store) -> None: ...
    def addNamespace(self, prefix, namespace): ...
    store: Incomplete
    def canonize(self) -> None: ...
    def reset(self) -> None: ...
    base: Incomplete
    def serialize(
        self,
        stream: IO[bytes],
        base: str | None = None,
        encoding: str | None = None,
        spacious: bool | None = None,
        **kwargs: Any,
    ) -> None: ...
    def preprocessTriple(self, triple: _TripleType) -> None: ...
    def getQName(self, uri, gen_prefix: bool = True): ...
    def startDocument(self) -> None: ...
    def endDocument(self) -> None: ...
    def statement(self, subject): ...
    def s_default(self, subject): ...
    def s_squared(self, subject): ...
    def path(self, node, position, newline: bool = False) -> None: ...
    def p_default(self, node, position, newline: bool = False): ...
    def label(self, node, position): ...
    def p_squared(self, node, position): ...
    def isValidList(self, l_): ...
    def doList(self, l_) -> None: ...
    def predicateList(self, subject, newline: bool = False) -> None: ...
    def verb(self, node, newline: bool = False) -> None: ...
    def objectList(self, objects) -> None: ...
