from _typeshed import Incomplete
from rdflib.graph import Graph, _PredicateType, _SubjectType, _TripleType
from rdflib.serializer import Serializer
from rdflib.term import Node, URIRef
from typing import Any, IO, Mapping, Sequence

__all__ = ["RecursiveSerializer", "TurtleSerializer"]

class RecursiveSerializer(Serializer):
    topClasses: Incomplete
    predicateOrder: Incomplete
    maxDepth: int
    indentString: str
    roundtrip_prefixes: tuple[Any, ...]
    stream: IO[bytes] | None
    def __init__(self, store: Graph) -> None: ...
    def addNamespace(self, prefix: str, uri: URIRef) -> None: ...
    def checkSubject(self, subject: _SubjectType) -> bool: ...
    def isDone(self, subject: _SubjectType) -> bool: ...
    def orderSubjects(self) -> list[_SubjectType]: ...
    def preprocess(self) -> None: ...
    def preprocessTriple(self, spo: _TripleType) -> None: ...
    depth: int
    lists: dict[None, None]
    namespaces: dict[str, URIRef]
    def reset(self) -> None: ...
    def buildPredicateHash(
        self, subject: _SubjectType
    ) -> Mapping[_PredicateType, list[Node]]: ...
    def sortProperties(
        self, properties: Mapping[_PredicateType, list[Node]]
    ) -> list[_PredicateType]: ...
    def subjectDone(self, subject: _SubjectType) -> None: ...
    def indent(self, modifier: int = 0) -> str: ...
    def write(self, text: str) -> None: ...
    def relativize(self, uri: _StrT) -> _StrT | URIRef: ...

class TurtleSerializer(RecursiveSerializer):
    short_name: str
    indentString: str
    keywords: dict[Node, str]
    stream: Incomplete
    def __init__(self, store: Graph) -> None: ...
    def addNamespace(self, prefix: str, namespace: URIRef) -> str: ...
    def reset(self) -> None: ...
    base: Incomplete
    def serialize(
        self,
        stream: IO[bytes],
        base: str | None = None,
        encoding: str | None = None,
        spacious: bool | None = None,
        **kwargs: Any,
    ) -> None: ...
    def preprocessTriple(self, triple: _TripleType) -> None: ...
    def getQName(self, uri: Node, gen_prefix: bool = True) -> str | None: ...
    def startDocument(self) -> None: ...
    def endDocument(self) -> None: ...
    def statement(self, subject: _SubjectType) -> bool: ...
    def s_default(self, subject: _SubjectType) -> bool: ...
    def s_squared(self, subject: _SubjectType) -> bool: ...
    def path(self, node: Node, position: int, newline: bool = False) -> None: ...
    def p_default(self, node: Node, position: int, newline: bool = False) -> bool: ...
    def label(self, node: Node, position: int) -> str: ...
    def p_squared(self, node: Node, position: int, newline: bool = False) -> bool: ...
    def isValidList(self, l_: Node) -> bool: ...
    def doList(self, l_: Node) -> None: ...
    def predicateList(self, subject: Node, newline: bool = False) -> None: ...
    def verb(self, node: Node, newline: bool = False) -> None: ...
    def objectList(self, objects: Sequence[Node]) -> None: ...
