from _typeshed import Incomplete
from rdflib.graph import Graph as Graph
from rdflib.namespace import RDF as RDF
from rdflib.term import (
    BNode as BNode,
    Identifier as Identifier,
    Literal as Literal,
    URIRef as URIRef,
)

class Describer:
    graph: Incomplete
    base: Incomplete
    def __init__(self, graph=None, about=None, base=None) -> None: ...
    def about(self, subject, **kws) -> None: ...
    def value(self, p, v, **kws) -> None: ...
    def rel(self, p, o=None, **kws): ...
    def rev(self, p, s=None, **kws): ...
    def rdftype(self, t) -> None: ...

def cast_value(v, **kws): ...
def cast_identifier(ref, **kws): ...
