from _typeshed import Incomplete
from collections.abc import Generator
from rdflib.namespace import Namespace

__all__ = [
    "ACE_NS",
    "AllClasses",
    "AllDifferent",
    "AllProperties",
    "AnnotatableTerms",
    "BooleanClass",
    "CLASS_RELATIONS",
    "Callable",
    "CastClass",
    "Class",
    "ClassNamespaceFactory",
    "CommonNSBindings",
    "ComponentTerms",
    "DeepClassClear",
    "EnumeratedClass",
    "GetIdentifiedClasses",
    "Individual",
    "Infix",
    "MalformedClass",
    "MalformedClassError",
    "OWLRDFListProxy",
    "Ontology",
    "Property",
    "PropertyAbstractSyntax",
    "Restriction",
    "classOrIdentifier",
    "classOrTerm",
    "exactly",
    "generateQName",
    "manchesterSyntax",
    "max",
    "min",
    "nsBinds",
    "only",
    "propertyOrIdentifier",
    "some",
    "value",
]

class Infix:
    function: Incomplete
    def __init__(self, function) -> None: ...
    def __rlshift__(self, other): ...
    def __rshift__(self, other): ...
    def __rmatmul__(self, other): ...
    def __matmul__(self, other): ...
    def __call__(self, value1, value2): ...

nsBinds: Incomplete

def generateQName(graph, uri): ...
def classOrTerm(thing): ...
def classOrIdentifier(thing): ...
def propertyOrIdentifier(thing): ...
def manchesterSyntax(thing, store, boolean=None, transientList: bool = False): ...
def GetIdentifiedClasses(graph) -> Generator[Incomplete]: ...

class TermDeletionHelper:
    prop: Incomplete
    def __init__(self, prop) -> None: ...
    def __call__(self, f): ...

class Individual:
    factoryGraph: Incomplete
    def serialize(self, graph) -> None: ...
    graph: Incomplete
    qname: Incomplete
    def __init__(self, identifier=None, graph=None) -> None: ...
    def clearInDegree(self) -> None: ...
    def clearOutDegree(self) -> None: ...
    def delete(self) -> None: ...
    def replace(self, other) -> None: ...
    type: Incomplete
    identifier: Incomplete
    sameAs: Incomplete

ACE_NS: Incomplete

class AnnotatableTerms(Individual):
    label: Incomplete
    def __init__(
        self, identifier, graph=None, nameAnnotation=None, nameIsLabel: bool = False
    ) -> None: ...
    def handleAnnotation(self, val): ...
    PN_sgprop: Incomplete
    CN_sgprop: Incomplete
    CN_plprop: Incomplete
    tv_sgprop: Incomplete
    tv_plprop: Incomplete
    tv_vbgprop: Incomplete
    def setupACEAnnotations(self) -> None: ...
    comment: Incomplete
    seeAlso: Incomplete

class Ontology(AnnotatableTerms):
    imports: Incomplete
    comment: Incomplete
    def __init__(
        self, identifier=None, imports=None, comment=None, graph=None
    ) -> None: ...
    def setVersion(self, version) -> None: ...

def AllClasses(graph) -> Generator[Incomplete]: ...
def AllProperties(graph) -> Generator[Incomplete]: ...

class ClassNamespaceFactory(Namespace):
    def term(self, name): ...
    def __getitem__(self, key, default=None): ...
    def __getattr__(self, name): ...

CLASS_RELATIONS: Incomplete

def ComponentTerms(cls) -> Generator[Incomplete]: ...
def DeepClassClear(class_to_prune) -> None: ...

class MalformedClass(ValueError): ...

class MalformedClassError(MalformedClass):
    msg: Incomplete
    def __init__(self, msg) -> None: ...

def CastClass(c, graph=None): ...

class Class(AnnotatableTerms):
    def serialize(self, graph) -> None: ...
    def setupNounAnnotations(self, noun_annotations) -> None: ...
    subClassOf: Incomplete
    equivalentClass: Incomplete
    disjointWith: Incomplete
    complementOf: Incomplete
    comment: Incomplete
    def __init__(
        self,
        identifier=None,
        subClassOf=None,
        equivalentClass=None,
        disjointWith=None,
        complementOf=None,
        graph=None,
        skipOWLClassMembership: bool = False,
        comment=None,
        nounAnnotations=None,
        nameAnnotation=None,
        nameIsLabel: bool = False,
    ) -> None: ...
    extent: Incomplete
    annotation: Incomplete
    extentQuery: Incomplete
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __iadd__(self, other): ...
    def __isub__(self, other): ...
    def __invert__(self): ...
    def __or__(self, other): ...
    def __and__(self, other): ...
    parents: Incomplete
    def isPrimitive(self): ...
    def subSumpteeIds(self) -> Generator[Incomplete]: ...
    def manchesterClass(self, full: bool = False, normalization: bool = True): ...

class OWLRDFListProxy:
    graph: Incomplete
    def __init__(self, rdf_list, members=None, graph=None) -> None: ...
    def __eq__(self, other): ...
    def __len__(self) -> int: ...
    def index(self, item): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def clear(self) -> None: ...
    def __iter__(self): ...
    def __contains__(self, item) -> bool: ...
    def append(self, item) -> None: ...
    def __iadd__(self, other): ...

class EnumeratedClass(OWLRDFListProxy, Class):
    def isPrimitive(self): ...
    def __init__(self, identifier=None, members=None, graph=None) -> None: ...
    def serialize(self, graph) -> None: ...

class BooleanClassExtentHelper:
    operator: Incomplete
    def __init__(self, operator) -> None: ...
    def __call__(self, f): ...

class Callable:
    def __init__(self, anycallable) -> None: ...
    def __call__(self, *args, **kwargs): ...

class BooleanClass(OWLRDFListProxy, Class):
    @Callable
    def getIntersections() -> None: ...
    getIntersections: Incomplete
    @Callable
    def getUnions() -> None: ...
    getUnions: Incomplete
    def __init__(
        self, identifier=None, operator=..., members=None, graph=None
    ) -> None: ...
    def copy(self): ...
    def serialize(self, graph) -> None: ...
    def isPrimitive(self): ...
    def changeOperator(self, newOperator) -> None: ...
    def __or__(self, other): ...

def AllDifferent(members) -> None: ...

class Restriction(Class):
    restrictionKinds: Incomplete
    onProperty: Incomplete
    restrictionType: Incomplete
    restrictionRange: Incomplete
    def __init__(
        self,
        onProperty,
        graph=None,
        allValuesFrom=None,
        someValuesFrom=None,
        value=None,
        cardinality=None,
        maxCardinality=None,
        minCardinality=None,
        identifier=None,
    ) -> None: ...
    def serialize(self, graph) -> None: ...
    def isPrimitive(self): ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    allValuesFrom: Incomplete
    someValuesFrom: Incomplete
    hasValue: Incomplete
    cardinality: Incomplete
    maxCardinality: Incomplete
    minCardinality: Incomplete
    def restrictionKind(self): ...

some: Incomplete
only: Incomplete
max: Incomplete
min: Incomplete
exactly: Incomplete
value: Incomplete
PropertyAbstractSyntax: str

class Property(AnnotatableTerms):
    def setupVerbAnnotations(self, verb_annotations) -> None: ...
    subPropertyOf: Incomplete
    inverseOf: Incomplete
    domain: Incomplete
    range: Incomplete
    comment: Incomplete
    def __init__(
        self,
        identifier=None,
        graph=None,
        baseType=...,
        subPropertyOf=None,
        domain=None,
        range=None,
        inverseOf=None,
        otherType=None,
        equivalentProperty=None,
        comment=None,
        verbAnnotations=None,
        nameAnnotation=None,
        nameIsLabel: bool = False,
    ) -> None: ...
    def serialize(self, graph) -> None: ...
    extent: Incomplete
    def replace(self, other) -> None: ...

def CommonNSBindings(graph, additionalNS=None) -> None: ...
