$schema: https://json-schema.org/draft/2020-12/schema
$id: https://www.wikidata.org/schemas/entitybase/endorsechange/1.0.0
title: EndorseChange
description: Schema for endorsement change events
type: object
properties:
  statement_hash:
    type: string
    description: Hash of the statement being endorsed
  user_id:
    type: string
    description: ID of the user performing the endorsement action
  action:
    type: string
    enum: [endorse, withdraw]
    description: Action taken on the endorsement
  timestamp:
    type: string
    format: date-time
    description: Timestamp of the endorsement action
required: [statement_hash, user_id, action, timestamp]