from _typeshed import Incomplete
from rdflib.graph import Graph
from rdflib.term import Node
from typing import Iterable, Iterator

__all__ = ["Collection"]

class Collection:
    graph: Incomplete
    uri: Incomplete
    def __init__(self, graph: Graph, uri: Node, seq: list[Node] = []) -> None: ...
    def n3(self) -> str: ...
    def __len__(self) -> int: ...
    def index(self, item: Node) -> int: ...
    def __getitem__(self, key: int) -> Node: ...
    def __setitem__(self, key: int, value: Node) -> None: ...
    def __delitem__(self, key: int) -> None: ...
    def __iter__(self) -> Iterator[Node]: ...
    def append(self, item: Node) -> Collection: ...
    def __iadd__(self, other: Iterable[Node]): ...
    def clear(self): ...
