from _typeshed import Incomplete

def cast_bytes(s, enc: str = "utf-8"): ...
def ascii(stream): ...
def bopen(*args, **kwargs): ...

long_type = int

def sign(n): ...

r_unicodeEscape: Incomplete

def decodeStringEscape(s): ...
def decodeUnicodeEscape(escaped: str) -> str: ...
