from _typeshed import Incomplete
from typing import Any

def cast_bytes(s: str | bytes, enc: str = "utf-8") -> bytes: ...
def ascii(stream) -> Any: ...
def bopen(*args, **kwargs) -> Any: ...

long_type = int

def sign(n: int | float) -> int: ...

r_unicodeEscape: Incomplete

def decodeStringEscape(s: str) -> str: ...
def decodeUnicodeEscape(escaped: str) -> str: ...
