from _typeshed import Incomplete
from rdflib.graph import ConjunctiveGraph, Graph, ReadOnlyGraphAggregate
from rdflib.term import IdentifiedNode, URIRef
from typing import Callable

__all__ = [
    "IsomorphicGraph",
    "to_isomorphic",
    "isomorphic",
    "to_canonical_graph",
    "graph_diff",
    "similar",
]

class _runtime:
    label: Incomplete
    def __init__(self, label) -> None: ...
    def __call__(self, f): ...

class _call_count:
    label: Incomplete
    def __init__(self, label) -> None: ...
    def __call__(self, f): ...

class IsomorphicGraph(ConjunctiveGraph):
    def __init__(self, **kwargs) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...
    def graph_digest(self, stats=None): ...
    def internal_hash(self, stats=None): ...

HashFunc = Callable[[str], int]
ColorItem = tuple[int | str, URIRef, int | str]
ColorItemTuple = tuple[ColorItem, ...]
HashCache = dict[ColorItemTuple, str] | None
Stats = dict[str, int | str]

class Color:
    color: Incomplete
    nodes: Incomplete
    hashfunc: Incomplete
    def __init__(
        self,
        nodes: list[IdentifiedNode],
        hashfunc: HashFunc,
        color: ColorItemTuple = (),
        hash_cache: HashCache = None,
    ) -> None: ...
    def key(self): ...
    def hash_color(self, color: tuple[ColorItem, ...] | None = None) -> str: ...
    def distinguish(self, W: Color, graph: Graph): ...
    def discrete(self): ...
    def copy(self): ...

class _TripleCanonicalizer:
    graph: Incomplete
    hashfunc: Incomplete
    def __init__(self, graph: Graph, hashfunc: _HashT = ...) -> None: ...
    def to_hash(self, stats: Stats | None = None): ...
    def canonical_triples(self, stats: Stats | None = None): ...

def to_isomorphic(graph: Graph) -> IsomorphicGraph: ...
def isomorphic(graph1: Graph, graph2: Graph) -> bool: ...
def to_canonical_graph(
    g1: Graph, stats: Stats | None = None
) -> ReadOnlyGraphAggregate: ...
def graph_diff(g1: Graph, g2: Graph) -> tuple[Graph, Graph, Graph]: ...
def similar(g1: Graph, g2: Graph): ...
