from typing import Any

__all__ = ["Event", "Dispatcher"]

class Event:
    def __init__(self, **kw: Any) -> None: ...

class Dispatcher:
    def set_map(self, amap: dict[Any, Any]): ...
    def get_map(self) -> dict[Any, Any] | None: ...
    def subscribe(self, event_type: Any, handler: Any) -> Any: ...
    def dispatch(self, event: Event) -> None: ...
