from _typeshed import Incomplete
from email.message import Message
from io import BufferedIOBase, BytesIO, RawIOBase, StringIO, TextIOBase
from rdflib.graph import Graph
from typing import Any, BinaryIO, TextIO
from typing_extensions import Buffer
from urllib.response import addinfourl
from xml.sax import xmlreader

__all__ = [
    "Parser",
    "InputSource",
    "StringInputSource",
    "URLInputSource",
    "FileInputSource",
    "PythonInputSource",
]

class Parser:
    def __init__(self) -> None: ...
    def parse(self, source: InputSource, sink: Graph) -> None: ...

class BytesIOWrapper(BufferedIOBase):
    wrapped: Incomplete
    encoding: Incomplete
    encoder: Incomplete
    enc_str: BytesIO | BufferedIOBase | None
    text_str: StringIO | TextIOBase | None
    has_read1: bool | None
    has_seek: bool | None
    def __init__(
        self, wrapped: str | StringIO | TextIOBase, encoding: str = "utf-8"
    ) -> None: ...
    @property
    def name(self) -> Any: ...
    @property
    def closed(self) -> bool: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def truncate(self, size: int | None = None) -> int: ...
    def isatty(self) -> bool: ...
    def fileno(self) -> int: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def read(self, size: int | None = -1, /) -> bytes: ...
    def read1(self, size: int | None = -1, /) -> bytes: ...
    def readinto(self, b: Buffer, /) -> int: ...
    def readinto1(self, b: Buffer, /) -> int: ...
    def seek(self, offset: int, whence: int = 0, /) -> int: ...
    def seekable(self): ...
    def tell(self) -> int: ...
    def write(self, b, /) -> None: ...

class InputSource(xmlreader.InputSource):
    content_type: str | None
    auto_close: bool
    def __init__(self, system_id: str | None = None) -> None: ...
    def close(self) -> None: ...

class PythonInputSource(InputSource):
    content_type: Incomplete
    auto_close: bool
    public_id: str | None
    system_id: str | None
    data: Incomplete
    def __init__(self, data: Any, system_id: str | None = None) -> None: ...
    def getPublicId(self) -> str | None: ...
    def setPublicId(self, public_id: str | None) -> None: ...
    def getSystemId(self) -> str | None: ...
    def setSystemId(self, system_id: str | None) -> None: ...
    def close(self) -> None: ...

class StringInputSource(InputSource):
    def __init__(
        self, value: str | bytes, encoding: str = "utf-8", system_id: str | None = None
    ) -> None: ...

class URLInputSource(InputSource):
    links: list[str]
    @classmethod
    def getallmatchingheaders(cls, message: Message, name) -> list[str]: ...
    @classmethod
    def get_links(cls, response: addinfourl) -> list[str]: ...
    def get_alternates(self, type_: str | None = None) -> list[str]: ...
    url: Incomplete
    content_type: Incomplete
    response_info: Incomplete
    def __init__(
        self, system_id: str | None = None, format: str | None = None
    ) -> None: ...

class FileInputSource(InputSource):
    file: Incomplete
    def __init__(
        self,
        file: BinaryIO | TextIO | TextIOBase | RawIOBase | BufferedIOBase,
        /,
        encoding: str | None = None,
    ) -> None: ...
