from _typeshed import Incomplete
from rdflib.events import Event
from rdflib.graph import (
    Graph,
    _ContextType,
    _QuadType,
    _TripleChoiceType,
    _TriplePatternType,
    _TripleType,
)
from rdflib.plugins.sparql.sparql import Query, Update
from rdflib.query import Result
from rdflib.term import Identifier, Node, URIRef
from typing import Any, Generator, Iterable, Iterator, Mapping

__all__ = [
    "StoreCreatedEvent",
    "TripleAddedEvent",
    "TripleRemovedEvent",
    "NodePickler",
    "Store",
]

class StoreCreatedEvent(Event): ...
class TripleAddedEvent(Event): ...
class TripleRemovedEvent(Event): ...

class NodePickler:
    def __init__(self) -> None: ...
    def register(self, object: Any, id: str) -> None: ...
    def loads(self, s: bytes) -> Node: ...
    def dumps(self, obj: Node, protocol: Any | None = None, bin: Any | None = None): ...

class Store:
    context_aware: bool
    formula_aware: bool
    transaction_aware: bool
    graph_aware: bool
    dispatcher: Incomplete
    def __init__(
        self, configuration: str | None = None, identifier: Identifier | None = None
    ) -> None: ...
    @property
    def node_pickler(self) -> NodePickler: ...
    def create(self, configuration: str) -> None: ...
    def open(
        self, configuration: str | tuple[str, str], create: bool = False
    ) -> int | None: ...
    def close(self, commit_pending_transaction: bool = False) -> None: ...
    def destroy(self, configuration: str) -> None: ...
    def gc(self) -> None: ...
    def add(
        self, triple: _TripleType, context: _ContextType, quoted: bool = False
    ) -> None: ...
    def addN(self, quads: Iterable[_QuadType]) -> None: ...
    def remove(
        self, triple: _TriplePatternType, context: _ContextType | None = None
    ) -> None: ...
    def triples_choices(
        self, triple: _TripleChoiceType, context: _ContextType | None = None
    ) -> Generator[tuple[_TripleType, Iterator[_ContextType | None]], None, None]: ...
    def triples(
        self, triple_pattern: _TriplePatternType, context: _ContextType | None = None
    ) -> Iterator[tuple[_TripleType, Iterator[_ContextType | None]]]: ...
    def __len__(self, context: _ContextType | None = None) -> int: ...
    def contexts(
        self, triple: _TripleType | None = None
    ) -> Generator[_ContextType, None, None]: ...
    def query(
        self,
        query: Query | str,
        initNs: Mapping[str, Any],
        initBindings: Mapping[str, Identifier],
        queryGraph: str,
        **kwargs: Any,
    ) -> Result: ...
    def update(
        self,
        update: Update | str,
        initNs: Mapping[str, Any],
        initBindings: Mapping[str, Identifier],
        queryGraph: str,
        **kwargs: Any,
    ) -> None: ...
    def bind(self, prefix: str, namespace: URIRef, override: bool = True) -> None: ...
    def prefix(self, namespace: URIRef) -> str | None: ...
    def namespace(self, prefix: str) -> URIRef | None: ...
    def namespaces(self) -> Iterator[tuple[str, URIRef]]: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def add_graph(self, graph: Graph) -> None: ...
    def remove_graph(self, graph: Graph) -> None: ...
