import abc
from .namespace import NamespaceManager
from .paths import AlternativePath, InvPath, NegatedPath, Path, SequencePath
from _typeshed import Incomplete
from typing import Any, Callable, Generator

__all__ = [
    "bind",
    "_is_valid_uri",
    "Node",
    "IdentifiedNode",
    "Identifier",
    "URIRef",
    "BNode",
    "Literal",
    "Variable",
]

def _is_valid_uri(uri: str) -> bool: ...

class Node(abc.ABC, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def n3(self, namespace_manager: NamespaceManager | None = None) -> str: ...

class Identifier(Node, str, metaclass=abc.ABCMeta):
    def __new__(cls, value: str): ...
    def eq(self, other: Any) -> bool: ...
    def neq(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def startswith(self, prefix: str, start=..., end=...) -> bool: ...
    __hash__: Incomplete

class IdentifiedNode(Identifier):
    def __getnewargs__(self) -> tuple[str]: ...
    def n3(self, namespace_manager: NamespaceManager | None = None) -> str: ...
    def toPython(self) -> str: ...

class URIRef(IdentifiedNode):
    __or__: Callable[[URIRef, URIRef | Path], AlternativePath]
    __invert__: Callable[[URIRef], InvPath]
    __neg__: Callable[[URIRef], NegatedPath]
    __truediv__: Callable[[URIRef, URIRef | Path], SequencePath]
    def __new__(cls, value: str, base: str | None = None): ...
    def n3(self, namespace_manager: NamespaceManager | None = None) -> str: ...
    def defrag(self) -> URIRef: ...
    @property
    def fragment(self) -> str: ...
    def __reduce__(self) -> tuple[type[URIRef], tuple[str]]: ...
    def __add__(self, other) -> URIRef: ...
    def __radd__(self, other) -> URIRef: ...
    def __mod__(self, other) -> URIRef: ...
    def de_skolemize(self) -> BNode: ...

class Genid(URIRef): ...
class RDFLibGenid(Genid): ...

class BNode(IdentifiedNode):
    def __new__(
        cls,
        value: str | None = None,
        _sn_gen: Callable[[], str] | Generator | None = None,
        _prefix: str = ...,
    ): ...
    def n3(self, namespace_manager: NamespaceManager | None = None) -> str: ...
    def __reduce__(self) -> tuple[type[BNode], tuple[str]]: ...
    def skolemize(
        self, authority: str | None = None, basepath: str | None = None
    ) -> URIRef: ...

class Literal(Identifier):
    def __new__(
        cls,
        lexical_or_value: Any,
        lang: str | None = None,
        datatype: str | None = None,
        normalize: bool | None = None,
    ): ...
    def normalize(self) -> Literal: ...
    @property
    def ill_typed(self) -> bool | None: ...
    @property
    def value(self) -> Any: ...
    @property
    def language(self) -> str | None: ...
    @property
    def datatype(self) -> URIRef | None: ...
    def __reduce__(
        self,
    ) -> tuple[type[Literal], tuple[str, str | None, str | None]]: ...
    def __add__(self, val: Any) -> Literal: ...
    def __sub__(self, val: Any) -> Literal: ...
    def __bool__(self) -> bool: ...
    def __neg__(self) -> Literal: ...
    def __pos__(self) -> Literal: ...
    def __abs__(self) -> Literal: ...
    def __invert__(self) -> Literal: ...
    def __gt__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def eq(self, other: Any) -> bool: ...
    def neq(self, other: Any) -> bool: ...
    def n3(self, namespace_manager: NamespaceManager | None = None) -> str: ...
    def toPython(self) -> Any: ...

def bind(
    datatype: str,
    pythontype: type[Any],
    constructor: Callable[[str], Any] | None = None,
    lexicalizer: Callable[[Any], str | bytes] | None = None,
    datatype_specific: bool = False,
) -> None: ...

class Variable(Identifier):
    def __new__(cls, value: str): ...
    def toPython(self) -> str: ...
    def n3(self, namespace_manager: NamespaceManager | None = None) -> str: ...
    def __reduce__(self) -> tuple[type[Variable], tuple[str]]: ...
