from _typeshed import Incomplete
from datetime import date, datetime, timedelta
from decimal import Decimal

def fquotmod(
    val: Decimal, low: Decimal | int, high: Decimal | int
) -> tuple[int, Decimal]: ...
def max_days_in_month(year: int, month: int) -> int: ...

class Duration:
    months: Incomplete
    years: Incomplete
    tdelta: Incomplete
    def __init__(
        self,
        days: float = 0,
        seconds: float = 0,
        microseconds: float = 0,
        milliseconds: float = 0,
        minutes: float = 0,
        hours: float = 0,
        weeks: float = 0,
        months: Decimal | float | int | str = 0,
        years: Decimal | float | int | str = 0,
    ) -> None: ...
    def __getattr__(self, name): ...
    def __hash__(self): ...
    def __neg__(self): ...
    def __add__(self, other: Duration | timedelta | date | datetime): ...
    __radd__ = __add__
    def __mul__(self, other): ...
    __rmul__ = __mul__
    def __sub__(self, other: Duration | timedelta): ...
    def __rsub__(self, other: timedelta | date | datetime): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def totimedelta(self, start=None, end=None): ...

ISO8601_PERIOD_REGEX: Incomplete

def parse_xsd_duration(
    dur_string: str, as_timedelta_if_possible: bool = True
) -> Duration | timedelta: ...
def duration_isoformat(tdt: Duration | timedelta, in_weeks: bool = False) -> str: ...
def xsd_datetime_isoformat(dt: datetime): ...
def parse_xsd_date(date_string: str): ...
