$schema: https://json-schema.org/draft/2020-12/schema
title: EntityBase Entities List Response
description: Schema for EntityBase entities list API responses
type: object
properties:
  entities:
    type: array
    items:
      type: object
      properties:
        entity_id:
          type: string
          pattern: ^[QPLEN][0-9]+$
          description: Entity ID
        id:
          type: string
          pattern: ^[QPLEN][0-9]+$
          description: Entity ID (alternative field name)
        revision_id:
          type: integer
          minimum: 1
          description: Revision ID
        head_revision_id:
          type: integer
          minimum: 1
          description: Head revision ID
        edit_type:
          type: string
          description: Edit type classification
      additionalProperties: true
    description: List of entity metadata objects
  count:
    type: integer
    minimum: 0
    description: Total number of entities returned
required:
- entities
- count
additionalProperties: false
