from _typeshed import Incomplete
from rdflib.graph import Graph, _TripleType
from rdflib.parser import InputSource, Parser
from rdflib.plugins.parsers.RDFVOC import RDFVOC
from rdflib.term import Identifier, URIRef
from typing import Any, NoReturn
from xml.sax import handler, xmlreader
from xml.sax.xmlreader import AttributesImpl, Locator

__all__ = ["create_parser", "BagID", "ElementHandler", "RDFXMLHandler", "RDFXMLParser"]

RDFNS = RDFVOC

class BagID(URIRef):
    li: int
    def __init__(self, val) -> None: ...
    def next_li(self): ...

class ElementHandler:
    start: Incomplete
    char: Incomplete
    end: Incomplete
    li: int
    id: Incomplete
    base: Incomplete
    subject: Incomplete
    object: Incomplete
    list: Incomplete
    language: Incomplete
    datatype: Incomplete
    declared: Incomplete
    data: Incomplete
    def __init__(self) -> None: ...
    def next_li(self): ...

class RDFXMLHandler(handler.ContentHandler):
    store: Incomplete
    preserve_bnode_ids: bool
    def __init__(self, store: Graph) -> None: ...
    stack: list[ElementHandler | None]
    ids: dict[str, int]
    bnode: dict[str, Identifier]
    def reset(self) -> None: ...
    locator: Incomplete
    def setDocumentLocator(self, locator: Locator): ...
    def startDocument(self) -> None: ...
    def startPrefixMapping(self, prefix: str | None, namespace: str) -> None: ...
    def endPrefixMapping(self, prefix: str | None) -> None: ...
    def startElementNS(
        self, name: tuple[str | None, str], qname, attrs: AttributesImpl
    ) -> None: ...
    def endElementNS(self, name: tuple[str | None, str], qname) -> None: ...
    def characters(self, content: str) -> None: ...
    def ignorableWhitespace(self, content) -> None: ...
    def processingInstruction(self, target, data) -> None: ...
    def add_reified(self, sid: Identifier, spo: _TripleType): ...
    def error(self, message: str) -> NoReturn: ...
    def get_current(self) -> ElementHandler | None: ...
    current: Incomplete
    def get_next(self) -> ElementHandler | None: ...
    next: Incomplete
    def get_parent(self) -> ElementHandler | None: ...
    parent: Incomplete
    def absolutize(self, uri: str) -> URIRef: ...
    def convert(
        self, name: tuple[str | None, str], qname, attrs: AttributesImpl
    ) -> tuple[URIRef, dict[URIRef, str]]: ...
    def document_element_start(
        self, name: tuple[str, str], qname, attrs: AttributesImpl
    ) -> None: ...
    def node_element_start(
        self, name: tuple[str, str], qname, attrs: AttributesImpl
    ) -> None: ...
    def node_element_end(self, name: tuple[str, str], qname) -> None: ...
    def property_element_start(
        self, name: tuple[str, str], qname, attrs: AttributesImpl
    ) -> None: ...
    def property_element_char(self, data: str) -> None: ...
    def property_element_end(self, name: tuple[str, str], qname) -> None: ...
    def list_node_element_end(self, name: tuple[str, str], qname) -> None: ...
    def literal_element_start(
        self, name: tuple[str, str], qname, attrs: AttributesImpl
    ) -> None: ...
    def literal_element_char(self, data: str) -> None: ...
    def literal_element_end(self, name: tuple[str, str], qname) -> None: ...

def create_parser(target: InputSource, store: Graph) -> xmlreader.XMLReader: ...

class RDFXMLParser(Parser):
    def __init__(self) -> None: ...
    def parse(self, source: InputSource, sink: Graph, **args: Any) -> None: ...
