from rdflib.graph import Graph as Graph
from rdflib.paths import Path as Path
from rdflib.plugins.sparql import CUSTOM_EVALS as CUSTOM_EVALS, parser as parser
from rdflib.plugins.sparql.aggregates import Aggregator as Aggregator
from rdflib.plugins.sparql.parserutils import CompValue as CompValue, value as value
from rdflib.plugins.sparql.sparql import (
    AlreadyBound as AlreadyBound,
    FrozenBindings as FrozenBindings,
    FrozenDict as FrozenDict,
    Query as Query,
    QueryContext as QueryContext,
    SPARQLError as SPARQLError,
)
from rdflib.term import (
    BNode as BNode,
    Identifier as Identifier,
    Literal as Literal,
    URIRef as URIRef,
    Variable as Variable,
)
from typing import Any, Generator, Iterable, Mapping

def evalBGP(
    ctx: QueryContext, bgp: list[_Triple]
) -> Generator[FrozenBindings, None, None]: ...
def evalExtend(
    ctx: QueryContext, extend: CompValue
) -> Generator[FrozenBindings, None, None]: ...
def evalLazyJoin(
    ctx: QueryContext, join: CompValue
) -> Generator[FrozenBindings, None, None]: ...
def evalJoin(
    ctx: QueryContext, join: CompValue
) -> Generator[FrozenDict, None, None]: ...
def evalUnion(ctx: QueryContext, union: CompValue) -> list[Any]: ...
def evalMinus(
    ctx: QueryContext, minus: CompValue
) -> Generator[FrozenDict, None, None]: ...
def evalLeftJoin(
    ctx: QueryContext, join: CompValue
) -> Generator[FrozenBindings, None, None]: ...
def evalFilter(
    ctx: QueryContext, part: CompValue
) -> Generator[FrozenBindings, None, None]: ...
def evalGraph(
    ctx: QueryContext, part: CompValue
) -> Generator[FrozenBindings, None, None]: ...
def evalValues(
    ctx: QueryContext, part: CompValue
) -> Generator[FrozenBindings, None, None]: ...
def evalMultiset(ctx: QueryContext, part: CompValue): ...
def evalPart(ctx: QueryContext, part: CompValue) -> Any: ...
def evalServiceQuery(ctx: QueryContext, part: CompValue): ...
def evalGroup(ctx: QueryContext, group: CompValue): ...
def evalAggregateJoin(
    ctx: QueryContext, agg: CompValue
) -> Generator[FrozenBindings, None, None]: ...
def evalOrderBy(
    ctx: QueryContext, part: CompValue
) -> Generator[FrozenBindings, None, None]: ...
def evalSlice(ctx: QueryContext, slice: CompValue): ...
def evalReduced(
    ctx: QueryContext, part: CompValue
) -> Generator[FrozenBindings, None, None]: ...
def evalDistinct(
    ctx: QueryContext, part: CompValue
) -> Generator[FrozenBindings, None, None]: ...
def evalProject(ctx: QueryContext, project: CompValue): ...
def evalSelectQuery(
    ctx: QueryContext, query: CompValue
) -> Mapping[str, str | list[Variable] | Iterable[FrozenDict]]: ...
def evalAskQuery(ctx: QueryContext, query: CompValue) -> Mapping[str, str | bool]: ...
def evalConstructQuery(
    ctx: QueryContext, query: CompValue
) -> Mapping[str, str | Graph]: ...
def evalDescribeQuery(ctx: QueryContext, query) -> dict[str, str | Graph]: ...
def evalQuery(
    graph: Graph,
    query: Query,
    initBindings: Mapping[str, Identifier] | None = None,
    base: str | None = None,
) -> Mapping[Any, Any]: ...
