import datetime
import typing as t
from _typeshed import Incomplete
from collections.abc import Mapping, MutableMapping
from rdflib.graph import (
    ConjunctiveGraph as ConjunctiveGraph,
    Dataset as Dataset,
    Graph as Graph,
)
from rdflib.namespace import NamespaceManager as NamespaceManager
from rdflib.paths import Path as Path
from rdflib.plugins.sparql.parserutils import CompValue as CompValue
from rdflib.term import (
    BNode as BNode,
    Identifier as Identifier,
    Literal as Literal,
    Node as Node,
    URIRef as URIRef,
    Variable as Variable,
)
from typing import Any, Container, Generator, Iterable

class SPARQLError(Exception):
    def __init__(self, msg: str | None = None) -> None: ...

class NotBoundError(SPARQLError):
    def __init__(self, msg: str | None = None) -> None: ...

class AlreadyBound(SPARQLError):
    def __init__(self) -> None: ...

class SPARQLTypeError(SPARQLError):
    def __init__(self, msg: str | None) -> None: ...

class Bindings(MutableMapping):
    outer: Incomplete
    def __init__(self, outer: Bindings | None = None, d=[]) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __contains__(self, key: Any) -> bool: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Generator[str, None, None]: ...

class FrozenDict(Mapping):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Identifier) -> Identifier: ...
    def __hash__(self) -> int: ...
    def project(self, vars: Container[Variable]) -> FrozenDict: ...
    def disjointDomain(self, other: t.Mapping[Identifier, Identifier]) -> bool: ...
    def compatible(self, other: t.Mapping[Identifier, Identifier]) -> bool: ...
    def merge(self, other: t.Mapping[Identifier, Identifier]) -> FrozenDict: ...

class FrozenBindings(FrozenDict):
    ctx: Incomplete
    def __init__(self, ctx: QueryContext, *args, **kwargs) -> None: ...
    def __getitem__(self, key: Identifier | str) -> Identifier: ...
    def project(self, vars: Container[Variable]) -> FrozenBindings: ...
    def merge(self, other: t.Mapping[Identifier, Identifier]) -> FrozenBindings: ...
    @property
    def now(self) -> datetime.datetime: ...
    @property
    def bnodes(self) -> t.Mapping[Identifier, BNode]: ...
    @property
    def prologue(self) -> Prologue | None: ...
    def forget(
        self, before: QueryContext, _except: Container[Variable] | None = None
    ) -> FrozenBindings: ...
    def remember(self, these) -> FrozenBindings: ...

class QueryContext:
    initBindings: Incomplete
    bindings: Incomplete
    graph: Graph | None
    prologue: Prologue | None
    bnodes: t.MutableMapping[Identifier, BNode]
    def __init__(
        self,
        graph: Graph | None = None,
        bindings: Bindings | FrozenBindings | list[Any] | None = None,
        initBindings: Mapping[str, Identifier] | None = None,
        datasetClause=None,
    ) -> None: ...
    @property
    def now(self) -> datetime.datetime: ...
    def clone(
        self, bindings: FrozenBindings | Bindings | list[Any] | None = None
    ) -> QueryContext: ...
    @property
    def dataset(self) -> ConjunctiveGraph: ...
    def load(
        self,
        source: URIRef,
        default: bool = False,
        into: Identifier | None = None,
        **kwargs: Any,
    ) -> None: ...
    def __getitem__(self, key: str | Path) -> str | Path | None: ...
    def get(self, key: str, default: Any | None = None) -> Any: ...
    def solution(self, vars: Iterable[Variable] | None = None) -> FrozenBindings: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def pushGraph(self, graph: Graph | None) -> QueryContext: ...
    def push(self) -> QueryContext: ...
    def clean(self) -> QueryContext: ...
    def thaw(self, frozenbindings: FrozenBindings) -> QueryContext: ...

class Prologue:
    base: str | None
    namespace_manager: Incomplete
    def __init__(self) -> None: ...
    def resolvePName(self, prefix: str | None, localname: str | None) -> URIRef: ...
    def bind(self, prefix: str | None, uri: Any) -> None: ...
    def absolutize(self, iri: CompValue | str | None) -> CompValue | str | None: ...

class Query:
    prologue: Incomplete
    algebra: Incomplete
    def __init__(self, prologue: Prologue, algebra: CompValue) -> None: ...

class Update:
    prologue: Incomplete
    algebra: Incomplete
    def __init__(self, prologue: Prologue, algebra: list[CompValue]) -> None: ...
