# type: ignore[misc]
from .types import Schema as Schema
from _typeshed import Incomplete
from io import BytesIO
from typing import Any, ClassVar
from typing_extensions import Self

class Struct:
    SCHEMA: ClassVar
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def encode(self) -> bytes: ...
    @classmethod
    def decode(cls, data: BytesIO | bytes) -> Self: ...
    def get_item(self, name: str) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    __hash__: Incomplete
