from _typeshed import Incomplete
from pyparsing import ParseResults
from rdflib.paths import (
    AlternativePath as AlternativePath,
    InvPath as InvPath,
    MulPath as MulPath,
    NegatedPath as NegatedPath,
    Path as Path,
    SequencePath as SequencePath,
)
from rdflib.plugins.sparql.operators import TrueFilter as TrueFilter, and_ as and_
from rdflib.plugins.sparql.parserutils import CompValue as CompValue, Expr as Expr
from rdflib.plugins.sparql.sparql import (
    Prologue as Prologue,
    Query as Query,
    Update as Update,
)
from rdflib.term import (
    BNode as BNode,
    Identifier as Identifier,
    Literal as Literal,
    URIRef as URIRef,
    Variable as Variable,
)
from typing import Any, Callable, DefaultDict, Iterable, Mapping, overload

def OrderBy(p: CompValue, expr: list[CompValue]) -> CompValue: ...
def ToMultiSet(p: list[dict[Variable, str]] | CompValue) -> CompValue: ...
def Union(p1: CompValue, p2: CompValue) -> CompValue: ...
def Join(p1: CompValue, p2: CompValue | None) -> CompValue: ...
def Minus(p1: CompValue, p2: CompValue) -> CompValue: ...
def Graph(term: Identifier, graph: CompValue) -> CompValue: ...
def BGP(
    triples: list[tuple[Identifier, Identifier, Identifier]] | None = None,
) -> CompValue: ...
def LeftJoin(p1: CompValue, p2: CompValue, expr) -> CompValue: ...
def Filter(expr: Expr, p: CompValue) -> CompValue: ...
def Extend(p: CompValue, expr: Identifier | Expr, var: Variable) -> CompValue: ...
def Values(res: list[dict[Variable, str]]) -> CompValue: ...
def Project(p: CompValue, PV: list[Variable]) -> CompValue: ...
def Group(p: CompValue, expr: list[Variable] | None = None) -> CompValue: ...
def reorderTriples(
    l_: Iterable[tuple[Identifier, Identifier, Identifier]],
) -> list[tuple[Identifier, Identifier, Identifier]]: ...
def triples(
    l: list[list[Identifier]] | list[tuple[Identifier, Identifier, Identifier]],
) -> list[tuple[Identifier, Identifier, Identifier]]: ...
def translatePName(p: CompValue | str, prologue: Prologue) -> Identifier | None: ...
@overload
def translatePath(p: URIRef) -> None: ...
@overload
def translatePath(p: CompValue) -> Path: ...
def translateExists(
    e: Expr | Literal | Variable | URIRef,
) -> Expr | Literal | Variable | URIRef: ...
def collectAndRemoveFilters(parts: list[CompValue]) -> Expr | None: ...
def translateGroupOrUnionGraphPattern(graphPattern: CompValue) -> CompValue | None: ...
def translateGraphGraphPattern(graphPattern: CompValue) -> CompValue: ...
def translateInlineData(graphPattern: CompValue) -> CompValue: ...
def translateGroupGraphPattern(graphPattern: CompValue) -> CompValue: ...

class StopTraversal(Exception):
    rv: Incomplete
    def __init__(self, rv: bool) -> None: ...

def traverse(
    tree,
    visitPre: Callable[[Any], Any] = ...,
    visitPost: Callable[[Any], Any] = ...,
    complete: bool | None = None,
) -> Any: ...
def translateAggregates(
    q: CompValue, M: CompValue
) -> tuple[CompValue, list[tuple[Variable, Variable]]]: ...
def translateValues(v: CompValue) -> list[dict[Variable, str]] | CompValue: ...
def translate(q: CompValue) -> tuple[CompValue | None, list[Variable]]: ...
def simplify(n: Any) -> CompValue | None: ...
def analyse(n: Any, children: Any) -> bool: ...
def translatePrologue(
    p: ParseResults,
    base: str | None,
    initNs: Mapping[str, Any] | None = None,
    prologue: Prologue | None = None,
) -> Prologue: ...
def translateQuads(
    quads: CompValue,
) -> tuple[
    list[tuple[Identifier, Identifier, Identifier]],
    DefaultDict[str, list[tuple[Identifier, Identifier, Identifier]]],
]: ...
def translateUpdate1(u: CompValue, prologue: Prologue) -> CompValue: ...
def translateUpdate(
    q: CompValue, base: str | None = None, initNs: Mapping[str, Any] | None = None
) -> Update: ...
def translateQuery(
    q: ParseResults, base: str | None = None, initNs: Mapping[str, Any] | None = None
) -> Query: ...

class ExpressionNotCoveredException(Exception): ...

class _AlgebraTranslator:
    query_algebra: Incomplete
    aggr_vars: DefaultDict[Identifier, list[Identifier]]
    def __init__(self, query_algebra: Query) -> None: ...
    def convert_node_arg(
        self, node_arg: Identifier | CompValue | Expr | str
    ) -> str: ...
    def sparql_query_text(self, node): ...
    def translateAlgebra(self) -> str: ...

def translateAlgebra(query_algebra: Query) -> str: ...
def pprintAlgebra(q) -> None: ...
