from rdflib.graph import Graph as Graph
from rdflib.plugins.sparql.evaluate import evalBGP as evalBGP, evalPart as evalPart
from rdflib.plugins.sparql.parserutils import CompValue as CompValue
from rdflib.plugins.sparql.sparql import (
    FrozenDict as FrozenDict,
    QueryContext as QueryContext,
    Update as Update,
)
from rdflib.term import Identifier as Identifier, URIRef as URIRef, Variable as Variable
from typing import Mapping

def evalLoad(ctx: QueryContext, u: CompValue) -> None: ...
def evalCreate(ctx: QueryContext, u: CompValue) -> None: ...
def evalClear(ctx: QueryContext, u: CompValue) -> None: ...
def evalDrop(ctx: QueryContext, u: CompValue) -> None: ...
def evalInsertData(ctx: QueryContext, u: CompValue) -> None: ...
def evalDeleteData(ctx: QueryContext, u: CompValue) -> None: ...
def evalDeleteWhere(ctx: QueryContext, u: CompValue) -> None: ...
def evalModify(ctx: QueryContext, u: CompValue) -> None: ...
def evalAdd(ctx: QueryContext, u: CompValue) -> None: ...
def evalMove(ctx: QueryContext, u: CompValue) -> None: ...
def evalCopy(ctx: QueryContext, u: CompValue) -> None: ...
def evalUpdate(
    graph: Graph, update: Update, initBindings: Mapping[str, Identifier] | None = None
) -> None: ...
